//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace BibliotecaEsocial.Model.S2205
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.esocial.gov.br/schema/evt/evtAltCadastral/v_S_01_00_00")]
    [System.Xml.Serialization.XmlRootAttribute(
        Namespace = "http://www.esocial.gov.br/schema/evt/evtAltCadastral/v_S_01_00_00", IsNullable = false)]
    public partial class eSocial
    {

        private eSocialEvtAltCadastral evtAltCadastralField;

        /// <remarks/>
        public eSocialEvtAltCadastral evtAltCadastral
        {
            get { return this.evtAltCadastralField; }
            set { this.evtAltCadastralField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.esocial.gov.br/schema/evt/evtAltCadastral/v_S_01_00_00")]
    public partial class eSocialEvtAltCadastral
    {

        private T_ideEvento_trab ideEventoField;

        private T_ideEmpregador ideEmpregadorField;

        private eSocialEvtAltCadastralIdeTrabalhador ideTrabalhadorField;

        private eSocialEvtAltCadastralAlteracao alteracaoField;

        private string idField;

        /// <remarks/>
        public T_ideEvento_trab ideEvento
        {
            get { return this.ideEventoField; }
            set { this.ideEventoField = value; }
        }

        /// <remarks/>
        public T_ideEmpregador ideEmpregador
        {
            get { return this.ideEmpregadorField; }
            set { this.ideEmpregadorField = value; }
        }

        /// <remarks/>
        public eSocialEvtAltCadastralIdeTrabalhador ideTrabalhador
        {
            get { return this.ideTrabalhadorField; }
            set { this.ideTrabalhadorField = value; }
        }

        /// <remarks/>
        public eSocialEvtAltCadastralAlteracao alteracao
        {
            get { return this.alteracaoField; }
            set { this.alteracaoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string Id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }
    }

    public partial class T_ideEvento_trab
    {

        private sbyte indRetifField;

        private string nrReciboField;

        private sbyte tpAmbField;

        private sbyte procEmiField;

        private string verProcField;

        /// <remarks/>
        public sbyte indRetif
        {
            get { return this.indRetifField; }
            set { this.indRetifField = value; }
        }

        /// <remarks/>
        public string nrRecibo
        {
            get { return this.nrReciboField; }
            set { this.nrReciboField = value; }
        }

        /// <remarks/>
        public sbyte tpAmb
        {
            get { return this.tpAmbField; }
            set { this.tpAmbField = value; }
        }

        /// <remarks/>
        public sbyte procEmi
        {
            get { return this.procEmiField; }
            set { this.procEmiField = value; }
        }

        /// <remarks/>
        public string verProc
        {
            get { return this.verProcField; }
            set { this.verProcField = value; }
        }
    }

    public partial class T_contato
    {

        private string fonePrincField;

        private string emailPrincField;

        /// <remarks/>
        public string fonePrinc
        {
            get { return this.fonePrincField; }
            set { this.fonePrincField = value; }
        }

        /// <remarks/>
        public string emailPrinc
        {
            get { return this.emailPrincField; }
            set { this.emailPrincField = value; }
        }
    }


    public partial class T_endereco_exterior
    {

        private string paisResidField;

        private string dscLogradField;

        private string nrLogradField;

        private string complementoField;

        private string bairroField;

        private string nmCidField;

        private string codPostalField;

        /// <remarks/>
        public string paisResid
        {
            get { return this.paisResidField; }
            set { this.paisResidField = value; }
        }

        /// <remarks/>
        public string dscLograd
        {
            get { return this.dscLogradField; }
            set { this.dscLogradField = value; }
        }

        /// <remarks/>
        public string nrLograd
        {
            get { return this.nrLogradField; }
            set { this.nrLogradField = value; }
        }

        /// <remarks/>
        public string complemento
        {
            get { return this.complementoField; }
            set { this.complementoField = value; }
        }

        /// <remarks/>
        public string bairro
        {
            get { return this.bairroField; }
            set { this.bairroField = value; }
        }

        /// <remarks/>
        public string nmCid
        {
            get { return this.nmCidField; }
            set { this.nmCidField = value; }
        }

        /// <remarks/>
        public string codPostal
        {
            get { return this.codPostalField; }
            set { this.codPostalField = value; }
        }
    }


    public partial class T_endereco_brasil
    {

        private string tpLogradField;

        private string dscLogradField;

        private string nrLogradField;

        private string complementoField;

        private string bairroField;

        private string cepField;

        private string codMunicField;

        private TS_uf ufField;

        /// <remarks/>
        public string tpLograd
        {
            get { return this.tpLogradField; }
            set { this.tpLogradField = value; }
        }

        /// <remarks/>
        public string dscLograd
        {
            get { return this.dscLogradField; }
            set { this.dscLogradField = value; }
        }

        /// <remarks/>
        public string nrLograd
        {
            get { return this.nrLogradField; }
            set { this.nrLogradField = value; }
        }

        /// <remarks/>
        public string complemento
        {
            get { return this.complementoField; }
            set { this.complementoField = value; }
        }

        /// <remarks/>
        public string bairro
        {
            get { return this.bairroField; }
            set { this.bairroField = value; }
        }

        /// <remarks/>
        public string cep
        {
            get { return this.cepField; }
            set { this.cepField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string codMunic
        {
            get { return this.codMunicField; }
            set { this.codMunicField = value; }
        }

        /// <remarks/>
        public TS_uf uf
        {
            get { return this.ufField; }
            set { this.ufField = value; }
        }
    }


    public enum TS_uf
    {

        /// <remarks/>
        AC,

        /// <remarks/>
        AL,

        /// <remarks/>
        AP,

        /// <remarks/>
        AM,

        /// <remarks/>
        BA,

        /// <remarks/>
        CE,

        /// <remarks/>
        DF,

        /// <remarks/>
        ES,

        /// <remarks/>
        GO,

        /// <remarks/>
        MA,

        /// <remarks/>
        MT,

        /// <remarks/>
        MS,

        /// <remarks/>
        MG,

        /// <remarks/>
        PA,

        /// <remarks/>
        PB,

        /// <remarks/>
        PR,

        /// <remarks/>
        PE,

        /// <remarks/>
        PI,

        /// <remarks/>
        RJ,

        /// <remarks/>
        RN,

        /// <remarks/>
        RS,

        /// <remarks/>
        RO,

        /// <remarks/>
        RR,

        /// <remarks/>
        SC,

        /// <remarks/>
        SP,

        /// <remarks/>
        SE,

        /// <remarks/>
        TO,
    }


    public partial class T_ideEmpregador
    {

        private sbyte tpInscField;

        private string nrInscField;

        /// <remarks/>
        public sbyte tpInsc
        {
            get { return this.tpInscField; }
            set { this.tpInscField = value; }
        }

        /// <remarks/>
        public string nrInsc
        {
            get { return this.nrInscField; }
            set { this.nrInscField = value; }
        }
    }

    public partial class eSocialEvtAltCadastralIdeTrabalhador
    {

        private string cpfTrabField;

        /// <remarks/>
        public string cpfTrab
        {
            get { return this.cpfTrabField; }
            set { this.cpfTrabField = value; }
        }
    }

    public partial class eSocialEvtAltCadastralAlteracao
    {

        private System.DateTime dtAlteracaoField;

        private eSocialEvtAltCadastralAlteracaoDadosTrabalhador dadosTrabalhadorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dtAlteracao
        {
            get { return this.dtAlteracaoField; }
            set { this.dtAlteracaoField = value; }
        }

        /// <remarks/>
        public eSocialEvtAltCadastralAlteracaoDadosTrabalhador dadosTrabalhador
        {
            get { return this.dadosTrabalhadorField; }
            set { this.dadosTrabalhadorField = value; }
        }
    }

    public partial class eSocialEvtAltCadastralAlteracaoDadosTrabalhador
    {

        private string nmTrabField;

        private TS_sexoTrab sexoField;

        private sbyte racaCorField;

        private sbyte estCivField;

        private bool estCivFieldSpecified;

        private TS_grauInstr grauInstrField;

        private string nmSocField;

        private string paisNacField;

        private eSocialEvtAltCadastralAlteracaoDadosTrabalhadorEndereco enderecoField;

        private eSocialEvtAltCadastralAlteracaoDadosTrabalhadorTrabImig trabImigField;

        private eSocialEvtAltCadastralAlteracaoDadosTrabalhadorInfoDeficiencia infoDeficienciaField;

        private eSocialEvtAltCadastralAlteracaoDadosTrabalhadorDependente[] dependenteField;

        private T_contato contatoField;

        /// <remarks/>
        public string nmTrab
        {
            get { return this.nmTrabField; }
            set { this.nmTrabField = value; }
        }

        /// <remarks/>
        public TS_sexoTrab sexo
        {
            get { return this.sexoField; }
            set { this.sexoField = value; }
        }

        /// <remarks/>
        public sbyte racaCor
        {
            get { return this.racaCorField; }
            set { this.racaCorField = value; }
        }

        /// <remarks/>
        public sbyte estCiv
        {
            get { return this.estCivField; }
            set { this.estCivField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estCivSpecified
        {
            get { return this.estCivFieldSpecified; }
            set { this.estCivFieldSpecified = value; }
        }

        /// <remarks/>
        public TS_grauInstr grauInstr
        {
            get { return this.grauInstrField; }
            set { this.grauInstrField = value; }
        }

        /// <remarks/>
        public string nmSoc
        {
            get { return this.nmSocField; }
            set { this.nmSocField = value; }
        }

        /// <remarks/>
        public string paisNac
        {
            get { return this.paisNacField; }
            set { this.paisNacField = value; }
        }

        /// <remarks/>
        public eSocialEvtAltCadastralAlteracaoDadosTrabalhadorEndereco endereco
        {
            get { return this.enderecoField; }
            set { this.enderecoField = value; }
        }

        /// <remarks/>
        public eSocialEvtAltCadastralAlteracaoDadosTrabalhadorTrabImig trabImig
        {
            get { return this.trabImigField; }
            set { this.trabImigField = value; }
        }

        /// <remarks/>
        public eSocialEvtAltCadastralAlteracaoDadosTrabalhadorInfoDeficiencia infoDeficiencia
        {
            get { return this.infoDeficienciaField; }
            set { this.infoDeficienciaField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dependente")]
        public eSocialEvtAltCadastralAlteracaoDadosTrabalhadorDependente[] dependente
        {
            get { return this.dependenteField; }
            set { this.dependenteField = value; }
        }

        /// <remarks/>
        public T_contato contato
        {
            get { return this.contatoField; }
            set { this.contatoField = value; }
        }
    }


    public enum TS_sexoTrab
    {

        /// <remarks/>
        M,

        /// <remarks/>
        F,
    }

    /// <remarks/>

    public enum TS_grauInstr
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
    }


    public partial class eSocialEvtAltCadastralAlteracaoDadosTrabalhadorEndereco
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brasil", typeof(T_endereco_brasil))]
        [System.Xml.Serialization.XmlElementAttribute("exterior", typeof(T_endereco_exterior))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }
    }


    public partial class eSocialEvtAltCadastralAlteracaoDadosTrabalhadorTrabImig
    {

        private sbyte tmpResidField;

        private bool tmpResidFieldSpecified;

        private sbyte condIngField;

        /// <remarks/>
        public sbyte tmpResid
        {
            get { return this.tmpResidField; }
            set { this.tmpResidField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tmpResidSpecified
        {
            get { return this.tmpResidFieldSpecified; }
            set { this.tmpResidFieldSpecified = value; }
        }

        /// <remarks/>
        public sbyte condIng
        {
            get { return this.condIngField; }
            set { this.condIngField = value; }
        }
    }


    public partial class eSocialEvtAltCadastralAlteracaoDadosTrabalhadorInfoDeficiencia
    {

        private TS_defFisica defFisicaField;

        private TS_defFisica defVisualField;

        private TS_defFisica defAuditivaField;

        private TS_defFisica defMentalField;

        private TS_defFisica defIntelectualField;

        private TS_defFisica reabReadapField;

        private TS_defFisica infoCotaField;

        private bool infoCotaFieldSpecified;

        private string observacaoField;

        /// <remarks/>
        public TS_defFisica defFisica
        {
            get { return this.defFisicaField; }
            set { this.defFisicaField = value; }
        }

        /// <remarks/>
        public TS_defFisica defVisual
        {
            get { return this.defVisualField; }
            set { this.defVisualField = value; }
        }

        /// <remarks/>
        public TS_defFisica defAuditiva
        {
            get { return this.defAuditivaField; }
            set { this.defAuditivaField = value; }
        }

        /// <remarks/>
        public TS_defFisica defMental
        {
            get { return this.defMentalField; }
            set { this.defMentalField = value; }
        }

        /// <remarks/>
        public TS_defFisica defIntelectual
        {
            get { return this.defIntelectualField; }
            set { this.defIntelectualField = value; }
        }

        /// <remarks/>
        public TS_defFisica reabReadap
        {
            get { return this.reabReadapField; }
            set { this.reabReadapField = value; }
        }

        /// <remarks/>
        public TS_defFisica infoCota
        {
            get { return this.infoCotaField; }
            set { this.infoCotaField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool infoCotaSpecified
        {
            get { return this.infoCotaFieldSpecified; }
            set { this.infoCotaFieldSpecified = value; }
        }

        /// <remarks/>
        public string observacao
        {
            get { return this.observacaoField; }
            set { this.observacaoField = value; }
        }
    }


    public enum TS_defFisica
    {

        /// <remarks/>
        S,

        /// <remarks/>
        N,
    }


    public partial class eSocialEvtAltCadastralAlteracaoDadosTrabalhadorDependente
    {

        private string tpDepField;

        private string nmDepField;

        private System.DateTime dtNasctoField;

        private string cpfDepField;

        private TS_sexoTrab sexoDepField;

        private bool sexoDepFieldSpecified;

        private TS_defFisica depIRRFField;

        private TS_defFisica depSFField;

        private TS_defFisica incTrabField;

        /// <remarks/>
        public string tpDep
        {
            get { return this.tpDepField; }
            set { this.tpDepField = value; }
        }

        /// <remarks/>
        public string nmDep
        {
            get { return this.nmDepField; }
            set { this.nmDepField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dtNascto
        {
            get { return this.dtNasctoField; }
            set { this.dtNasctoField = value; }
        }

        /// <remarks/>
        public string cpfDep
        {
            get { return this.cpfDepField; }
            set { this.cpfDepField = value; }
        }

        /// <remarks/>
        public TS_sexoTrab sexoDep
        {
            get { return this.sexoDepField; }
            set { this.sexoDepField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sexoDepSpecified
        {
            get { return this.sexoDepFieldSpecified; }
            set { this.sexoDepFieldSpecified = value; }
        }

        /// <remarks/>
        public TS_defFisica depIRRF
        {
            get { return this.depIRRFField; }
            set { this.depIRRFField = value; }
        }

        /// <remarks/>
        public TS_defFisica depSF
        {
            get { return this.depSFField; }
            set { this.depSFField = value; }
        }

        /// <remarks/>
        public TS_defFisica incTrab
        {
            get { return this.incTrabField; }
            set { this.incTrabField = value; }
        }
    }
}