//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace BibliotecaEsocial.Model.S2200
{

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtAdmissao/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtAdmissao/v_S_01_00_00", IsNullable=false)]
public  class eSocial {
    
    private eSocialEvtAdmissao evtAdmissaoField;
    
    /// <remarks/>
    public eSocialEvtAdmissao evtAdmissao {
        get {
            return this.evtAdmissaoField;
        }
        set {
            this.evtAdmissaoField = value;
        }
    }
}

public partial class eSocialEvtAdmissao {
    
    private T_ideEvento_trab_admissao ideEventoField;
    
    private T_ideEmpregador ideEmpregadorField;
    
    private eSocialEvtAdmissaoTrabalhador trabalhadorField;
    
    private eSocialEvtAdmissaoVinculo vinculoField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_trab_admissao ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoTrabalhador trabalhador {
        get {
            return this.trabalhadorField;
        }
        set {
            this.trabalhadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculo vinculo {
        get {
            return this.vinculoField;
        }
        set {
            this.vinculoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_trab_admissao {
    
    private sbyte indRetifField;
    
    private string nrReciboField;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indRetif {
        get {
            return this.indRetifField;
        }
        set {
            this.indRetifField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecibo {
        get {
            return this.nrReciboField;
        }
        set {
            this.nrReciboField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_treiCap {
    
    private string codTreiCapField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codTreiCap {
        get {
            return this.codTreiCapField;
        }
        set {
            this.codTreiCapField = value;
        }
    }
}


public partial class T_alvaraJudicial {
    
    private string nrProcJudField;
    
    /// <remarks/>
    public string nrProcJud {
        get {
            return this.nrProcJudField;
        }
        set {
            this.nrProcJudField = value;
        }
    }
}


public partial class T_horContratual {
    
    private decimal qtdHrsSemField;
    
    private bool qtdHrsSemFieldSpecified;
    
    private sbyte tpJornadaField;
    
    private sbyte tmpParcField;
    
    private TS_defFisica horNoturnoField;
    
    private bool horNoturnoFieldSpecified;
    
    private string dscJornField;
    
    /// <remarks/>
    public decimal qtdHrsSem {
        get {
            return this.qtdHrsSemField;
        }
        set {
            this.qtdHrsSemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool qtdHrsSemSpecified {
        get {
            return this.qtdHrsSemFieldSpecified;
        }
        set {
            this.qtdHrsSemFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpJornada {
        get {
            return this.tpJornadaField;
        }
        set {
            this.tpJornadaField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tmpParc {
        get {
            return this.tmpParcField;
        }
        set {
            this.tmpParcField = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica horNoturno {
        get {
            return this.horNoturnoField;
        }
        set {
            this.horNoturnoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool horNoturnoSpecified {
        get {
            return this.horNoturnoFieldSpecified;
        }
        set {
            this.horNoturnoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string dscJorn {
        get {
            return this.dscJornField;
        }
        set {
            this.dscJornField = value;
        }
    }
}


public enum TS_defFisica {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    N,
}


public partial class T_localTrabGeral {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    private string descCompField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
    
    /// <remarks/>
    public string descComp {
        get {
            return this.descCompField;
        }
        set {
            this.descCompField = value;
        }
    }
}


public partial class T_remuneracao {
    
    private decimal vrSalFxField;
    
    private sbyte undSalFixoField;
    
    private string dscSalVarField;
    
    /// <remarks/>
    public decimal vrSalFx {
        get {
            return this.vrSalFxField;
        }
        set {
            this.vrSalFxField = value;
        }
    }
    
    /// <remarks/>
    public sbyte undSalFixo {
        get {
            return this.undSalFixoField;
        }
        set {
            this.undSalFixoField = value;
        }
    }
    
    /// <remarks/>
    public string dscSalVar {
        get {
            return this.dscSalVarField;
        }
        set {
            this.dscSalVarField = value;
        }
    }
}


public partial class T_aprend {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class T_contato {
    
    private string fonePrincField;
    
    private string emailPrincField;
    
    /// <remarks/>
    public string fonePrinc {
        get {
            return this.fonePrincField;
        }
        set {
            this.fonePrincField = value;
        }
    }
    
    /// <remarks/>
    public string emailPrinc {
        get {
            return this.emailPrincField;
        }
        set {
            this.emailPrincField = value;
        }
    }
}


public partial class T_endereco_exterior {
    
    private string paisResidField;
    
    private string dscLogradField;
    
    private string nrLogradField;
    
    private string complementoField;
    
    private string bairroField;
    
    private string nmCidField;
    
    private string codPostalField;
    
    /// <remarks/>
    public string paisResid {
        get {
            return this.paisResidField;
        }
        set {
            this.paisResidField = value;
        }
    }
    
    /// <remarks/>
    public string dscLograd {
        get {
            return this.dscLogradField;
        }
        set {
            this.dscLogradField = value;
        }
    }
    
    /// <remarks/>
    public string nrLograd {
        get {
            return this.nrLogradField;
        }
        set {
            this.nrLogradField = value;
        }
    }
    
    /// <remarks/>
    public string complemento {
        get {
            return this.complementoField;
        }
        set {
            this.complementoField = value;
        }
    }
    
    /// <remarks/>
    public string bairro {
        get {
            return this.bairroField;
        }
        set {
            this.bairroField = value;
        }
    }
    
    /// <remarks/>
    public string nmCid {
        get {
            return this.nmCidField;
        }
        set {
            this.nmCidField = value;
        }
    }
    
    /// <remarks/>
    public string codPostal {
        get {
            return this.codPostalField;
        }
        set {
            this.codPostalField = value;
        }
    }
}


public partial class T_endereco_brasil {
    
    private string tpLogradField;
    
    private string dscLogradField;
    
    private string nrLogradField;
    
    private string complementoField;
    
    private string bairroField;
    
    private string cepField;
    
    private string codMunicField;
    
    private TS_uf ufField;
    
    /// <remarks/>
    public string tpLograd {
        get {
            return this.tpLogradField;
        }
        set {
            this.tpLogradField = value;
        }
    }
    
    /// <remarks/>
    public string dscLograd {
        get {
            return this.dscLogradField;
        }
        set {
            this.dscLogradField = value;
        }
    }
    
    /// <remarks/>
    public string nrLograd {
        get {
            return this.nrLogradField;
        }
        set {
            this.nrLogradField = value;
        }
    }
    
    /// <remarks/>
    public string complemento {
        get {
            return this.complementoField;
        }
        set {
            this.complementoField = value;
        }
    }
    
    /// <remarks/>
    public string bairro {
        get {
            return this.bairroField;
        }
        set {
            this.bairroField = value;
        }
    }
    
    /// <remarks/>
    public string cep {
        get {
            return this.cepField;
        }
        set {
            this.cepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codMunic {
        get {
            return this.codMunicField;
        }
        set {
            this.codMunicField = value;
        }
    }
    
    /// <remarks/>
    public TS_uf uf {
        get {
            return this.ufField;
        }
        set {
            this.ufField = value;
        }
    }
}


public enum TS_uf {
    
    /// <remarks/>
    AC,
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    AP,
    
    /// <remarks/>
    AM,
    
    /// <remarks/>
    BA,
    
    /// <remarks/>
    CE,
    
    /// <remarks/>
    DF,
    
    /// <remarks/>
    ES,
    
    /// <remarks/>
    GO,
    
    /// <remarks/>
    MA,
    
    /// <remarks/>
    MT,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MG,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    PB,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    PE,
    
    /// <remarks/>
    PI,
    
    /// <remarks/>
    RJ,
    
    /// <remarks/>
    RN,
    
    /// <remarks/>
    RS,
    
    /// <remarks/>
    RO,
    
    /// <remarks/>
    RR,
    
    /// <remarks/>
    SC,
    
    /// <remarks/>
    SP,
    
    /// <remarks/>
    SE,
    
    /// <remarks/>
    TO,
}


public partial class T_nascimento {
    
    private System.DateTime dtNasctoField;
    
    private string paisNasctoField;
    
    private string paisNacField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtNascto {
        get {
            return this.dtNasctoField;
        }
        set {
            this.dtNasctoField = value;
        }
    }
    
    /// <remarks/>
    public string paisNascto {
        get {
            return this.paisNasctoField;
        }
        set {
            this.paisNasctoField = value;
        }
    }
    
    /// <remarks/>
    public string paisNac {
        get {
            return this.paisNacField;
        }
        set {
            this.paisNacField = value;
        }
    }
}


public partial class T_ideEmpregador {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoTrabalhador {
    
    private string cpfTrabField;
    
    private string nmTrabField;
    
    private TS_sexoTrab sexoField;
    
    private sbyte racaCorField;
    
    private sbyte estCivField;
    
    private bool estCivFieldSpecified;
    
    private TS_grauInstr grauInstrField;
    
    private string nmSocField;
    
    private T_nascimento nascimentoField;
    
    private eSocialEvtAdmissaoTrabalhadorEndereco enderecoField;
    
    private eSocialEvtAdmissaoTrabalhadorTrabImig trabImigField;
    
    private eSocialEvtAdmissaoTrabalhadorInfoDeficiencia infoDeficienciaField;  
    
    private eSocialEvtAdmissaoTrabalhadorDependente[] dependenteField;
    
    private T_contato contatoField;
    
    /// <remarks/>
    public string cpfTrab {
        get {
            return this.cpfTrabField;
        }
        set {
            this.cpfTrabField = value;
        }
    }
    
    /// <remarks/>
    public string nmTrab {
        get {
            return this.nmTrabField;
        }
        set {
            this.nmTrabField = value;
        }
    }
    
    /// <remarks/>
    public TS_sexoTrab sexo {
        get {
            return this.sexoField;
        }
        set {
            this.sexoField = value;
        }
    }
    
    /// <remarks/>
    public sbyte racaCor {
        get {
            return this.racaCorField;
        }
        set {
            this.racaCorField = value;
        }
    }
    
    /// <remarks/>
    public sbyte estCiv {
        get {
            return this.estCivField;
        }
        set {
            this.estCivField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool estCivSpecified {
        get {
            return this.estCivFieldSpecified;
        }
        set {
            this.estCivFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public TS_grauInstr grauInstr {
        get {
            return this.grauInstrField;
        }
        set {
            this.grauInstrField = value;
        }
    }
    
    /// <remarks/>
    public string nmSoc {
        get {
            return this.nmSocField;
        }
        set {
            this.nmSocField = value;
        }
    }
    
    /// <remarks/>
    public T_nascimento nascimento {
        get {
            return this.nascimentoField;
        }
        set {
            this.nascimentoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoTrabalhadorEndereco endereco {
        get {
            return this.enderecoField;
        }
        set {
            this.enderecoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoTrabalhadorTrabImig trabImig {
        get {
            return this.trabImigField;
        }
        set {
            this.trabImigField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoTrabalhadorInfoDeficiencia infoDeficiencia {
        get {
            return this.infoDeficienciaField;
        }
        set {
            this.infoDeficienciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dependente")]
    public eSocialEvtAdmissaoTrabalhadorDependente[] dependente {
        get {
            return this.dependenteField;
        }
        set {
            this.dependenteField = value;
        }
    }
    
    /// <remarks/>
    public T_contato contato {
        get {
            return this.contatoField;
        }
        set {
            this.contatoField = value;
        }
    }
}


public enum TS_sexoTrab {
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    F,
}


public enum TS_grauInstr {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("01")]
    Item01,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("02")]
    Item02,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("03")]
    Item03,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("04")]
    Item04,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("05")]
    Item05,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("06")]
    Item06,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("07")]
    Item07,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("08")]
    Item08,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("09")]
    Item09,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
}


public partial class eSocialEvtAdmissaoTrabalhadorEndereco {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("brasil", typeof(T_endereco_brasil))]
    [System.Xml.Serialization.XmlElementAttribute("exterior", typeof(T_endereco_exterior))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoTrabalhadorTrabImig {
    
    private sbyte tmpResidField;
    
    private bool tmpResidFieldSpecified;
    
    private sbyte condIngField;
    
    /// <remarks/>
    public sbyte tmpResid {
        get {
            return this.tmpResidField;
        }
        set {
            this.tmpResidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tmpResidSpecified {
        get {
            return this.tmpResidFieldSpecified;
        }
        set {
            this.tmpResidFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public sbyte condIng {
        get {
            return this.condIngField;
        }
        set {
            this.condIngField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoTrabalhadorInfoDeficiencia {
    
    private TS_defFisica defFisicaField;
    
    private TS_defFisica defVisualField;
    
    private TS_defFisica defAuditivaField;
    
    private TS_defFisica defMentalField;
    
    private TS_defFisica defIntelectualField;
    
    private TS_defFisica reabReadapField;
    
    private TS_defFisica infoCotaField;
    
    private bool infoCotaFieldSpecified;
    
    private string observacaoField;
    
    /// <remarks/>
    public TS_defFisica defFisica {
        get {
            return this.defFisicaField;
        }
        set {
            this.defFisicaField = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica defVisual {
        get {
            return this.defVisualField;
        }
        set {
            this.defVisualField = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica defAuditiva {
        get {
            return this.defAuditivaField;
        }
        set {
            this.defAuditivaField = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica defMental {
        get {
            return this.defMentalField;
        }
        set {
            this.defMentalField = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica defIntelectual {
        get {
            return this.defIntelectualField;
        }
        set {
            this.defIntelectualField = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica reabReadap {
        get {
            return this.reabReadapField;
        }
        set {
            this.reabReadapField = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica infoCota {
        get {
            return this.infoCotaField;
        }
        set {
            this.infoCotaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool infoCotaSpecified {
        get {
            return this.infoCotaFieldSpecified;
        }
        set {
            this.infoCotaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string observacao {
        get {
            return this.observacaoField;
        }
        set {
            this.observacaoField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoTrabalhadorDependente {
    
    private string tpDepField;
    
    private string nmDepField;
    
    private System.DateTime dtNasctoField;
    
    private string cpfDepField;
    
    private TS_sexoTrab sexoDepField;
    
    private bool sexoDepFieldSpecified;
    
    private TS_defFisica depIRRFField;
    
    private TS_defFisica depSFField;
    
    private TS_defFisica incTrabField;
    
    /// <remarks/>
    public string tpDep {
        get {
            return this.tpDepField;
        }
        set {
            this.tpDepField = value;
        }
    }
    
    /// <remarks/>
    public string nmDep {
        get {
            return this.nmDepField;
        }
        set {
            this.nmDepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtNascto {
        get {
            return this.dtNasctoField;
        }
        set {
            this.dtNasctoField = value;
        }
    }
    
    /// <remarks/>
    public string cpfDep {
        get {
            return this.cpfDepField;
        }
        set {
            this.cpfDepField = value;
        }
    }
    
    /// <remarks/>
    public TS_sexoTrab sexoDep {
        get {
            return this.sexoDepField;
        }
        set {
            this.sexoDepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sexoDepSpecified {
        get {
            return this.sexoDepFieldSpecified;
        }
        set {
            this.sexoDepFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica depIRRF {
        get {
            return this.depIRRFField;
        }
        set {
            this.depIRRFField = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica depSF {
        get {
            return this.depSFField;
        }
        set {
            this.depSFField = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica incTrab {
        get {
            return this.incTrabField;
        }
        set {
            this.incTrabField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculo {
    
    private string matriculaField;
    
    private sbyte tpRegTrabField;
    
    private sbyte tpRegPrevField;
    
    private eSocialEvtAdmissaoVinculoCadIni cadIniField;
    
    private eSocialEvtAdmissaoVinculoInfoRegimeTrab infoRegimeTrabField;
    
    private eSocialEvtAdmissaoVinculoInfoContrato infoContratoField;
    
    private eSocialEvtAdmissaoVinculoSucessaoVinc sucessaoVincField;
    
    private eSocialEvtAdmissaoVinculoTransfDom transfDomField;
    
    private eSocialEvtAdmissaoVinculoMudancaCPF mudancaCPFField;
    
    private eSocialEvtAdmissaoVinculoAfastamento afastamentoField;
    
    private eSocialEvtAdmissaoVinculoDesligamento desligamentoField;
    
    private eSocialEvtAdmissaoVinculoCessao cessaoField;
    
    /// <remarks/>
    public string matricula {
        get {
            return this.matriculaField;
        }
        set {
            this.matriculaField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpRegTrab {
        get {
            return this.tpRegTrabField;
        }
        set {
            this.tpRegTrabField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpRegPrev {
        get {
            return this.tpRegPrevField;
        }
        set {
            this.tpRegPrevField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoCadIni cadIni {
        get {
            return this.cadIniField;
        }
        set {
            this.cadIniField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoInfoRegimeTrab infoRegimeTrab {
        get {
            return this.infoRegimeTrabField;
        }
        set {
            this.infoRegimeTrabField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoInfoContrato infoContrato {
        get {
            return this.infoContratoField;
        }
        set {
            this.infoContratoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoSucessaoVinc sucessaoVinc {
        get {
            return this.sucessaoVincField;
        }
        set {
            this.sucessaoVincField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoTransfDom transfDom {
        get {
            return this.transfDomField;
        }
        set {
            this.transfDomField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoMudancaCPF mudancaCPF {
        get {
            return this.mudancaCPFField;
        }
        set {
            this.mudancaCPFField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoAfastamento afastamento {
        get {
            return this.afastamentoField;
        }
        set {
            this.afastamentoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoDesligamento desligamento {
        get {
            return this.desligamentoField;
        }
        set {
            this.desligamentoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoCessao cessao {
        get {
            return this.cessaoField;
        }
        set {
            this.cessaoField = value;
        }
    }
}


public enum eSocialEvtAdmissaoVinculoCadIni {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    N,
}


public partial class eSocialEvtAdmissaoVinculoInfoRegimeTrab {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("infoCeletista", typeof(eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletista))]
    [System.Xml.Serialization.XmlElementAttribute("infoEstatutario", typeof(eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoEstatutario))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletista {
    
    private System.DateTime dtAdmField;
    
    private sbyte tpAdmissaoField;
    
    private sbyte indAdmissaoField;
    
    private string nrProcTrabField;
    
    private sbyte tpRegJorField;
    
    private sbyte natAtividadeField;
    
    private sbyte dtBaseField;
    
    private bool dtBaseFieldSpecified;
    
    private string cnpjSindCategProfField;
    
    private eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletistaFGTS fGTSField;
    
    private eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletistaTrabTemporario trabTemporarioField;
    
    private T_aprend aprendField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtAdm {
        get {
            return this.dtAdmField;
        }
        set {
            this.dtAdmField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAdmissao {
        get {
            return this.tpAdmissaoField;
        }
        set {
            this.tpAdmissaoField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indAdmissao {
        get {
            return this.indAdmissaoField;
        }
        set {
            this.indAdmissaoField = value;
        }
    }
    
    /// <remarks/>
    public string nrProcTrab {
        get {
            return this.nrProcTrabField;
        }
        set {
            this.nrProcTrabField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpRegJor {
        get {
            return this.tpRegJorField;
        }
        set {
            this.tpRegJorField = value;
        }
    }
    
    /// <remarks/>
    public sbyte natAtividade {
        get {
            return this.natAtividadeField;
        }
        set {
            this.natAtividadeField = value;
        }
    }
    
    /// <remarks/>
    public sbyte dtBase {
        get {
            return this.dtBaseField;
        }
        set {
            this.dtBaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dtBaseSpecified {
        get {
            return this.dtBaseFieldSpecified;
        }
        set {
            this.dtBaseFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string cnpjSindCategProf {
        get {
            return this.cnpjSindCategProfField;
        }
        set {
            this.cnpjSindCategProfField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletistaFGTS FGTS {
        get {
            return this.fGTSField;
        }
        set {
            this.fGTSField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletistaTrabTemporario trabTemporario {
        get {
            return this.trabTemporarioField;
        }
        set {
            this.trabTemporarioField = value;
        }
    }
    
    /// <remarks/>
    public T_aprend aprend {
        get {
            return this.aprendField;
        }
        set {
            this.aprendField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletistaFGTS {
    
    private System.DateTime dtOpcFGTSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtOpcFGTS {
        get {
            return this.dtOpcFGTSField;
        }
        set {
            this.dtOpcFGTSField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletistaTrabTemporario {
    
    private sbyte hipLegField;
    
    private string justContrField;
    
    private eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletistaTrabTemporarioIdeEstabVinc ideEstabVincField;
    
    private eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletistaTrabTemporarioIdeTrabSubstituido[] ideTrabSubstituidoField;
    
    /// <remarks/>
    public sbyte hipLeg {
        get {
            return this.hipLegField;
        }
        set {
            this.hipLegField = value;
        }
    }
    
    /// <remarks/>
    public string justContr {
        get {
            return this.justContrField;
        }
        set {
            this.justContrField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletistaTrabTemporarioIdeEstabVinc ideEstabVinc {
        get {
            return this.ideEstabVincField;
        }
        set {
            this.ideEstabVincField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ideTrabSubstituido")]
    public eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletistaTrabTemporarioIdeTrabSubstituido[] ideTrabSubstituido {
        get {
            return this.ideTrabSubstituidoField;
        }
        set {
            this.ideTrabSubstituidoField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletistaTrabTemporarioIdeEstabVinc {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoCeletistaTrabTemporarioIdeTrabSubstituido {
    
    private string cpfTrabSubstField;
    
    /// <remarks/>
    public string cpfTrabSubst {
        get {
            return this.cpfTrabSubstField;
        }
        set {
            this.cpfTrabSubstField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoInfoRegimeTrabInfoEstatutario {
    
    private sbyte tpProvField;
    
    private System.DateTime dtExercicioField;
    
    private sbyte tpPlanRPField;
    
    private bool tpPlanRPFieldSpecified;
    
    private TS_defFisica indTetoRGPSField;
    
    private bool indTetoRGPSFieldSpecified;
    
    private TS_defFisica indAbonoPermField;
    
    private bool indAbonoPermFieldSpecified;
    
    private System.DateTime dtIniAbonoField;
    
    private bool dtIniAbonoFieldSpecified;
    
    /// <remarks/>
    public sbyte tpProv {
        get {
            return this.tpProvField;
        }
        set {
            this.tpProvField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtExercicio {
        get {
            return this.dtExercicioField;
        }
        set {
            this.dtExercicioField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpPlanRP {
        get {
            return this.tpPlanRPField;
        }
        set {
            this.tpPlanRPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tpPlanRPSpecified {
        get {
            return this.tpPlanRPFieldSpecified;
        }
        set {
            this.tpPlanRPFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica indTetoRGPS {
        get {
            return this.indTetoRGPSField;
        }
        set {
            this.indTetoRGPSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indTetoRGPSSpecified {
        get {
            return this.indTetoRGPSFieldSpecified;
        }
        set {
            this.indTetoRGPSFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica indAbonoPerm {
        get {
            return this.indAbonoPermField;
        }
        set {
            this.indAbonoPermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indAbonoPermSpecified {
        get {
            return this.indAbonoPermFieldSpecified;
        }
        set {
            this.indAbonoPermFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtIniAbono {
        get {
            return this.dtIniAbonoField;
        }
        set {
            this.dtIniAbonoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dtIniAbonoSpecified {
        get {
            return this.dtIniAbonoFieldSpecified;
        }
        set {
            this.dtIniAbonoFieldSpecified = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoInfoContrato {
    
    private string nmCargoField;
    
    private string cBOCargoField;
    
    private System.DateTime dtIngrCargoField;
    
    private bool dtIngrCargoFieldSpecified;
    
    private string nmFuncaoField;
    
    private string cBOFuncaoField;
    
    private TS_defFisica acumCargoField;
    
    private bool acumCargoFieldSpecified;
    
    private string codCategField;
    
    private T_remuneracao remuneracaoField;
    
    private eSocialEvtAdmissaoVinculoInfoContratoDuracao duracaoField;
    
    private eSocialEvtAdmissaoVinculoInfoContratoLocalTrabalho localTrabalhoField;
    
    private T_horContratual horContratualField;
    
    private T_alvaraJudicial alvaraJudicialField;
    
    private eSocialEvtAdmissaoVinculoInfoContratoObservacoes[] observacoesField;
    
    private T_treiCap[] treiCapField;
    
    /// <remarks/>
    public string nmCargo {
        get {
            return this.nmCargoField;
        }
        set {
            this.nmCargoField = value;
        }
    }
    
    /// <remarks/>
    public string CBOCargo {
        get {
            return this.cBOCargoField;
        }
        set {
            this.cBOCargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtIngrCargo {
        get {
            return this.dtIngrCargoField;
        }
        set {
            this.dtIngrCargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dtIngrCargoSpecified {
        get {
            return this.dtIngrCargoFieldSpecified;
        }
        set {
            this.dtIngrCargoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string nmFuncao {
        get {
            return this.nmFuncaoField;
        }
        set {
            this.nmFuncaoField = value;
        }
    }
    
    /// <remarks/>
    public string CBOFuncao {
        get {
            return this.cBOFuncaoField;
        }
        set {
            this.cBOFuncaoField = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica acumCargo {
        get {
            return this.acumCargoField;
        }
        set {
            this.acumCargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool acumCargoSpecified {
        get {
            return this.acumCargoFieldSpecified;
        }
        set {
            this.acumCargoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codCateg {
        get {
            return this.codCategField;
        }
        set {
            this.codCategField = value;
        }
    }
    
    /// <remarks/>
    public T_remuneracao remuneracao {
        get {
            return this.remuneracaoField;
        }
        set {
            this.remuneracaoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoInfoContratoDuracao duracao {
        get {
            return this.duracaoField;
        }
        set {
            this.duracaoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtAdmissaoVinculoInfoContratoLocalTrabalho localTrabalho {
        get {
            return this.localTrabalhoField;
        }
        set {
            this.localTrabalhoField = value;
        }
    }
    
    /// <remarks/>
    public T_horContratual horContratual {
        get {
            return this.horContratualField;
        }
        set {
            this.horContratualField = value;
        }
    }
    
    /// <remarks/>
    public T_alvaraJudicial alvaraJudicial {
        get {
            return this.alvaraJudicialField;
        }
        set {
            this.alvaraJudicialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("observacoes")]
    public eSocialEvtAdmissaoVinculoInfoContratoObservacoes[] observacoes {
        get {
            return this.observacoesField;
        }
        set {
            this.observacoesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("treiCap")]
    public T_treiCap[] treiCap {
        get {
            return this.treiCapField;
        }
        set {
            this.treiCapField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoInfoContratoDuracao {
    
    private sbyte tpContrField;
    
    private System.DateTime dtTermField;
    
    private bool dtTermFieldSpecified;
    
    private TS_defFisica clauAssecField;
    
    private bool clauAssecFieldSpecified;
    
    private string objDetField;
    
    /// <remarks/>
    public sbyte tpContr {
        get {
            return this.tpContrField;
        }
        set {
            this.tpContrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtTerm {
        get {
            return this.dtTermField;
        }
        set {
            this.dtTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dtTermSpecified {
        get {
            return this.dtTermFieldSpecified;
        }
        set {
            this.dtTermFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public TS_defFisica clauAssec {
        get {
            return this.clauAssecField;
        }
        set {
            this.clauAssecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool clauAssecSpecified {
        get {
            return this.clauAssecFieldSpecified;
        }
        set {
            this.clauAssecFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string objDet {
        get {
            return this.objDetField;
        }
        set {
            this.objDetField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoInfoContratoLocalTrabalho {
    
    private T_localTrabGeral localTrabGeralField;
    
    private T_endereco_brasil localTempDomField;
    
    /// <remarks/>
    public T_localTrabGeral localTrabGeral {
        get {
            return this.localTrabGeralField;
        }
        set {
            this.localTrabGeralField = value;
        }
    }
    
    /// <remarks/>
    public T_endereco_brasil localTempDom {
        get {
            return this.localTempDomField;
        }
        set {
            this.localTempDomField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoInfoContratoObservacoes {
    
    private string observacaoField;
    
    /// <remarks/>
    public string observacao {
        get {
            return this.observacaoField;
        }
        set {
            this.observacaoField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoSucessaoVinc {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    private string matricAntField;
    
    private System.DateTime dtTransfField;
    
    private string observacaoField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
    
    /// <remarks/>
    public string matricAnt {
        get {
            return this.matricAntField;
        }
        set {
            this.matricAntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtTransf {
        get {
            return this.dtTransfField;
        }
        set {
            this.dtTransfField = value;
        }
    }
    
    /// <remarks/>
    public string observacao {
        get {
            return this.observacaoField;
        }
        set {
            this.observacaoField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoTransfDom {
    
    private string cpfSubstituidoField;
    
    private string matricAntField;
    
    private System.DateTime dtTransfField;
    
    /// <remarks/>
    public string cpfSubstituido {
        get {
            return this.cpfSubstituidoField;
        }
        set {
            this.cpfSubstituidoField = value;
        }
    }
    
    /// <remarks/>
    public string matricAnt {
        get {
            return this.matricAntField;
        }
        set {
            this.matricAntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtTransf {
        get {
            return this.dtTransfField;
        }
        set {
            this.dtTransfField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoMudancaCPF {
    
    private string cpfAntField;
    
    private string matricAntField;
    
    private System.DateTime dtAltCPFField;
    
    private string observacaoField;
    
    /// <remarks/>
    public string cpfAnt {
        get {
            return this.cpfAntField;
        }
        set {
            this.cpfAntField = value;
        }
    }
    
    /// <remarks/>
    public string matricAnt {
        get {
            return this.matricAntField;
        }
        set {
            this.matricAntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtAltCPF {
        get {
            return this.dtAltCPFField;
        }
        set {
            this.dtAltCPFField = value;
        }
    }
    
    /// <remarks/>
    public string observacao {
        get {
            return this.observacaoField;
        }
        set {
            this.observacaoField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoAfastamento {
    
    private System.DateTime dtIniAfastField;
    
    private string codMotAfastField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtIniAfast {
        get {
            return this.dtIniAfastField;
        }
        set {
            this.dtIniAfastField = value;
        }
    }
    
    /// <remarks/>
    public string codMotAfast {
        get {
            return this.codMotAfastField;
        }
        set {
            this.codMotAfastField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoDesligamento {
    
    private System.DateTime dtDesligField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtDeslig {
        get {
            return this.dtDesligField;
        }
        set {
            this.dtDesligField = value;
        }
    }
}


public partial class eSocialEvtAdmissaoVinculoCessao {
    
    private System.DateTime dtIniCessaoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtIniCessao {
        get {
            return this.dtIniCessaoField;
        }
        set {
            this.dtIniCessaoField = value;
        }
    }
}
}