//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace BibliotecaEsocial.Model.S1207
{


 
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtBenPrRP/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtBenPrRP/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtBenPrRP evtBenPrRPField;
    
    /// <remarks/>
    public eSocialEvtBenPrRP evtBenPrRP {
        get {
            return this.evtBenPrRPField;
        }
        set {
            this.evtBenPrRPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtBenPrRP/v_S_01_00_00")]
public partial class eSocialEvtBenPrRP {
    
    private T_ideEvento_folha_opp ideEventoField;
    
    private T_ideEmpregador_cnpj ideEmpregadorField;
    
    private eSocialEvtBenPrRPIdeBenef ideBenefField;
    
    private eSocialEvtBenPrRPDmDev[] dmDevField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_folha_opp ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador_cnpj ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtBenPrRPIdeBenef ideBenef {
        get {
            return this.ideBenefField;
        }
        set {
            this.ideBenefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dmDev")]
    public eSocialEvtBenPrRPDmDev[] dmDev {
        get {
            return this.dmDevField;
        }
        set {
            this.dmDevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_folha_opp {
    
    private sbyte indRetifField;
    
    private string nrReciboField;
    
    private sbyte indApuracaoField;
    
    private string perApurField;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indRetif {
        get {
            return this.indRetifField;
        }
        set {
            this.indRetifField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecibo {
        get {
            return this.nrReciboField;
        }
        set {
            this.nrReciboField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indApuracao {
        get {
            return this.indApuracaoField;
        }
        set {
            this.indApuracaoField = value;
        }
    }
    
    /// <remarks/>
    public string perApur {
        get {
            return this.perApurField;
        }
        set {
            this.perApurField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_itensRemun_rpps {
    
    private string codRubrField;
    
    private string ideTabRubrField;
    
    private decimal qtdRubrField;
    
    private bool qtdRubrFieldSpecified;
    
    private decimal fatorRubrField;
    
    private bool fatorRubrFieldSpecified;
    
    private decimal vrRubrField;
    
    private sbyte indApurIRField;
    
    /// <remarks/>
    public string codRubr {
        get {
            return this.codRubrField;
        }
        set {
            this.codRubrField = value;
        }
    }
    
    /// <remarks/>
    public string ideTabRubr {
        get {
            return this.ideTabRubrField;
        }
        set {
            this.ideTabRubrField = value;
        }
    }
    
    /// <remarks/>
    public decimal qtdRubr {
        get {
            return this.qtdRubrField;
        }
        set {
            this.qtdRubrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool qtdRubrSpecified {
        get {
            return this.qtdRubrFieldSpecified;
        }
        set {
            this.qtdRubrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal fatorRubr {
        get {
            return this.fatorRubrField;
        }
        set {
            this.fatorRubrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fatorRubrSpecified {
        get {
            return this.fatorRubrFieldSpecified;
        }
        set {
            this.fatorRubrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal vrRubr {
        get {
            return this.vrRubrField;
        }
        set {
            this.vrRubrField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indApurIR {
        get {
            return this.indApurIRField;
        }
        set {
            this.indApurIRField = value;
        }
    }
}


public partial class T_ideEstab {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    private T_itensRemun_rpps[] itensRemunField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("itensRemun")]
    public T_itensRemun_rpps[] itensRemun {
        get {
            return this.itensRemunField;
        }
        set {
            this.itensRemunField = value;
        }
    }
}


public partial class T_ideEmpregador_cnpj {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtBenPrRPIdeBenef {
    
    private string cpfBenefField;
    
    /// <remarks/>
    public string cpfBenef {
        get {
            return this.cpfBenefField;
        }
        set {
            this.cpfBenefField = value;
        }
    }
}


public partial class eSocialEvtBenPrRPDmDev {
    
    private string ideDmDevField;
    
    private string nrBeneficioField;
    
    private T_ideEstab[] infoPerApurField;
    
    private eSocialEvtBenPrRPDmDevIdePeriodo[] infoPerAntField;
    
    /// <remarks/>
    public string ideDmDev {
        get {
            return this.ideDmDevField;
        }
        set {
            this.ideDmDevField = value;
        }
    }
    
    /// <remarks/>
    public string nrBeneficio {
        get {
            return this.nrBeneficioField;
        }
        set {
            this.nrBeneficioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ideEstab", IsNullable=false)]
    public T_ideEstab[] infoPerApur {
        get {
            return this.infoPerApurField;
        }
        set {
            this.infoPerApurField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("idePeriodo", IsNullable=false)]
    public eSocialEvtBenPrRPDmDevIdePeriodo[] infoPerAnt {
        get {
            return this.infoPerAntField;
        }
        set {
            this.infoPerAntField = value;
        }
    }
}


public partial class eSocialEvtBenPrRPDmDevIdePeriodo {
    
    private string perRefField;
    
    private T_ideEstab[] ideEstabField;
    
    /// <remarks/>
    public string perRef {
        get {
            return this.perRefField;
        }
        set {
            this.perRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ideEstab")]
    public T_ideEstab[] ideEstab {
        get {
            return this.ideEstabField;
        }
        set {
            this.ideEstabField = value;
        }
    }
}
}