//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace BibliotecaEsocial.Model.S5011
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.esocial.gov.br/schema/evt/evtCS/v_S_01_00_00")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.esocial.gov.br/schema/evt/evtCS/v_S_01_00_00", IsNullable = false)]
    public partial class eSocial
    {

        private eSocialEvtCS evtCSField;

        /// <remarks/>
        public eSocialEvtCS evtCS
        {
            get
            {
                return this.evtCSField;
            }
            set
            {
                this.evtCSField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.esocial.gov.br/schema/evt/evtCS/v_S_01_00_00")]
    public partial class eSocialEvtCS
    {

        private T_ideEvento_retorno_contrib ideEventoField;

        private T_ideEmpregador ideEmpregadorField;

        private eSocialEvtCSInfoCS infoCSField;

        private string idField;

        /// <remarks/>
        public T_ideEvento_retorno_contrib ideEvento
        {
            get
            {
                return this.ideEventoField;
            }
            set
            {
                this.ideEventoField = value;
            }
        }

        /// <remarks/>
        public T_ideEmpregador ideEmpregador
        {
            get
            {
                return this.ideEmpregadorField;
            }
            set
            {
                this.ideEmpregadorField = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCS infoCS
        {
            get
            {
                return this.infoCSField;
            }
            set
            {
                this.infoCSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }


    public partial class T_ideEvento_retorno_contrib
    {

        private sbyte indApuracaoField;

        private string perApurField;

        /// <remarks/>
        public sbyte indApuracao
        {
            get
            {
                return this.indApuracaoField;
            }
            set
            {
                this.indApuracaoField = value;
            }
        }

        /// <remarks/>
        public string perApur
        {
            get
            {
                return this.perApurField;
            }
            set
            {
                this.perApurField = value;
            }
        }
    }

    public partial class T_ideEmpregador
    {

        private sbyte tpInscField;

        private string nrInscField;

        /// <remarks/>
        public sbyte tpInsc
        {
            get
            {
                return this.tpInscField;
            }
            set
            {
                this.tpInscField = value;
            }
        }

        /// <remarks/>
        public string nrInsc
        {
            get
            {
                return this.nrInscField;
            }
            set
            {
                this.nrInscField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCS
    {

        private string nrRecArqBaseField;

        private sbyte indExistInfoField;

        private eSocialEvtCSInfoCSInfoCPSeg infoCPSegField;

        private eSocialEvtCSInfoCSInfoContrib infoContribField;

        private eSocialEvtCSInfoCSIdeEstab[] ideEstabField;

        private eSocialEvtCSInfoCSInfoCRContrib[] infoCRContribField;

        /// <remarks/>
        public string nrRecArqBase
        {
            get
            {
                return this.nrRecArqBaseField;
            }
            set
            {
                this.nrRecArqBaseField = value;
            }
        }

        /// <remarks/>
        public sbyte indExistInfo
        {
            get
            {
                return this.indExistInfoField;
            }
            set
            {
                this.indExistInfoField = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCSInfoCPSeg infoCPSeg
        {
            get
            {
                return this.infoCPSegField;
            }
            set
            {
                this.infoCPSegField = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCSInfoContrib infoContrib
        {
            get
            {
                return this.infoContribField;
            }
            set
            {
                this.infoContribField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ideEstab")]
        public eSocialEvtCSInfoCSIdeEstab[] ideEstab
        {
            get
            {
                return this.ideEstabField;
            }
            set
            {
                this.ideEstabField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("infoCRContrib")]
        public eSocialEvtCSInfoCSInfoCRContrib[] infoCRContrib
        {
            get
            {
                return this.infoCRContribField;
            }
            set
            {
                this.infoCRContribField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSInfoCPSeg
    {

        private decimal vrDescCPField;

        private decimal vrCpSegField;

        /// <remarks/>
        public decimal vrDescCP
        {
            get
            {
                return this.vrDescCPField;
            }
            set
            {
                this.vrDescCPField = value;
            }
        }

        /// <remarks/>
        public decimal vrCpSeg
        {
            get
            {
                return this.vrCpSegField;
            }
            set
            {
                this.vrCpSegField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSInfoContrib
    {

        private string classTribField;

        private eSocialEvtCSInfoCSInfoContribInfoPJ infoPJField;

        /// <remarks/>
        public string classTrib
        {
            get
            {
                return this.classTribField;
            }
            set
            {
                this.classTribField = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCSInfoContribInfoPJ infoPJ
        {
            get
            {
                return this.infoPJField;
            }
            set
            {
                this.infoPJField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSInfoContribInfoPJ
    {

        private sbyte indCoopField;

        private bool indCoopFieldSpecified;

        private sbyte indConstrField;

        private sbyte indSubstPatrField;

        private bool indSubstPatrFieldSpecified;

        private decimal percRedContribField;

        private bool percRedContribFieldSpecified;

        private sbyte percTransfField;

        private bool percTransfFieldSpecified;

        private eSocialEvtCSInfoCSInfoContribInfoPJInfoAtConc infoAtConcField;

        /// <remarks/>
        public sbyte indCoop
        {
            get
            {
                return this.indCoopField;
            }
            set
            {
                this.indCoopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indCoopSpecified
        {
            get
            {
                return this.indCoopFieldSpecified;
            }
            set
            {
                this.indCoopFieldSpecified = value;
            }
        }

        /// <remarks/>
        public sbyte indConstr
        {
            get
            {
                return this.indConstrField;
            }
            set
            {
                this.indConstrField = value;
            }
        }

        /// <remarks/>
        public sbyte indSubstPatr
        {
            get
            {
                return this.indSubstPatrField;
            }
            set
            {
                this.indSubstPatrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indSubstPatrSpecified
        {
            get
            {
                return this.indSubstPatrFieldSpecified;
            }
            set
            {
                this.indSubstPatrFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal percRedContrib
        {
            get
            {
                return this.percRedContribField;
            }
            set
            {
                this.percRedContribField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool percRedContribSpecified
        {
            get
            {
                return this.percRedContribFieldSpecified;
            }
            set
            {
                this.percRedContribFieldSpecified = value;
            }
        }

        /// <remarks/>
        public sbyte percTransf
        {
            get
            {
                return this.percTransfField;
            }
            set
            {
                this.percTransfField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool percTransfSpecified
        {
            get
            {
                return this.percTransfFieldSpecified;
            }
            set
            {
                this.percTransfFieldSpecified = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCSInfoContribInfoPJInfoAtConc infoAtConc
        {
            get
            {
                return this.infoAtConcField;
            }
            set
            {
                this.infoAtConcField = value;
            }
        }
    }

    public partial class eSocialEvtCSInfoCSInfoContribInfoPJInfoAtConc
    {

        private decimal fatorMesField;

        private decimal fator13Field;

        /// <remarks/>
        public decimal fatorMes
        {
            get
            {
                return this.fatorMesField;
            }
            set
            {
                this.fatorMesField = value;
            }
        }

        /// <remarks/>
        public decimal fator13
        {
            get
            {
                return this.fator13Field;
            }
            set
            {
                this.fator13Field = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstab
    {

        private sbyte tpInscField;

        private string nrInscField;

        private eSocialEvtCSInfoCSIdeEstabInfoEstab infoEstabField;

        private eSocialEvtCSInfoCSIdeEstabIdeLotacao[] ideLotacaoField;

        private eSocialEvtCSInfoCSIdeEstabBasesAquis[] basesAquisField;

        private eSocialEvtCSInfoCSIdeEstabBasesComerc[] basesComercField;

        private eSocialEvtCSInfoCSIdeEstabInfoCREstab[] infoCREstabField;

        /// <remarks/>
        public sbyte tpInsc
        {
            get
            {
                return this.tpInscField;
            }
            set
            {
                this.tpInscField = value;
            }
        }

        /// <remarks/>
        public string nrInsc
        {
            get
            {
                return this.nrInscField;
            }
            set
            {
                this.nrInscField = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCSIdeEstabInfoEstab infoEstab
        {
            get
            {
                return this.infoEstabField;
            }
            set
            {
                this.infoEstabField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ideLotacao")]
        public eSocialEvtCSInfoCSIdeEstabIdeLotacao[] ideLotacao
        {
            get
            {
                return this.ideLotacaoField;
            }
            set
            {
                this.ideLotacaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("basesAquis")]
        public eSocialEvtCSInfoCSIdeEstabBasesAquis[] basesAquis
        {
            get
            {
                return this.basesAquisField;
            }
            set
            {
                this.basesAquisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("basesComerc")]
        public eSocialEvtCSInfoCSIdeEstabBasesComerc[] basesComerc
        {
            get
            {
                return this.basesComercField;
            }
            set
            {
                this.basesComercField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("infoCREstab")]
        public eSocialEvtCSInfoCSIdeEstabInfoCREstab[] infoCREstab
        {
            get
            {
                return this.infoCREstabField;
            }
            set
            {
                this.infoCREstabField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstabInfoEstab
    {

        private string cnaePrepField;

        private string cnpjRespField;

        private sbyte aliqRatField;

        private decimal fapField;

        private bool fapFieldSpecified;

        private decimal aliqRatAjustField;

        private bool aliqRatAjustFieldSpecified;

        private eSocialEvtCSInfoCSIdeEstabInfoEstabInfoEstabRef infoEstabRefField;

        private eSocialEvtCSInfoCSIdeEstabInfoEstabInfoComplObra infoComplObraField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string cnaePrep
        {
            get
            {
                return this.cnaePrepField;
            }
            set
            {
                this.cnaePrepField = value;
            }
        }

        /// <remarks/>
        public string cnpjResp
        {
            get
            {
                return this.cnpjRespField;
            }
            set
            {
                this.cnpjRespField = value;
            }
        }

        /// <remarks/>
        public sbyte aliqRat
        {
            get
            {
                return this.aliqRatField;
            }
            set
            {
                this.aliqRatField = value;
            }
        }

        /// <remarks/>
        public decimal fap
        {
            get
            {
                return this.fapField;
            }
            set
            {
                this.fapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fapSpecified
        {
            get
            {
                return this.fapFieldSpecified;
            }
            set
            {
                this.fapFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal aliqRatAjust
        {
            get
            {
                return this.aliqRatAjustField;
            }
            set
            {
                this.aliqRatAjustField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aliqRatAjustSpecified
        {
            get
            {
                return this.aliqRatAjustFieldSpecified;
            }
            set
            {
                this.aliqRatAjustFieldSpecified = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCSIdeEstabInfoEstabInfoEstabRef infoEstabRef
        {
            get
            {
                return this.infoEstabRefField;
            }
            set
            {
                this.infoEstabRefField = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCSIdeEstabInfoEstabInfoComplObra infoComplObra
        {
            get
            {
                return this.infoComplObraField;
            }
            set
            {
                this.infoComplObraField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstabInfoEstabInfoEstabRef
    {

        private sbyte aliqRatField;

        private decimal fapField;

        private bool fapFieldSpecified;

        private decimal aliqRatAjustField;

        private bool aliqRatAjustFieldSpecified;

        /// <remarks/>
        public sbyte aliqRat
        {
            get
            {
                return this.aliqRatField;
            }
            set
            {
                this.aliqRatField = value;
            }
        }

        /// <remarks/>
        public decimal fap
        {
            get
            {
                return this.fapField;
            }
            set
            {
                this.fapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fapSpecified
        {
            get
            {
                return this.fapFieldSpecified;
            }
            set
            {
                this.fapFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal aliqRatAjust
        {
            get
            {
                return this.aliqRatAjustField;
            }
            set
            {
                this.aliqRatAjustField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aliqRatAjustSpecified
        {
            get
            {
                return this.aliqRatAjustFieldSpecified;
            }
            set
            {
                this.aliqRatAjustFieldSpecified = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstabInfoEstabInfoComplObra
    {

        private sbyte indSubstPatrObraField;

        /// <remarks/>
        public sbyte indSubstPatrObra
        {
            get
            {
                return this.indSubstPatrObraField;
            }
            set
            {
                this.indSubstPatrObraField = value;
            }
        }
    }

    public partial class eSocialEvtCSInfoCSIdeEstabIdeLotacao
    {

        private string codLotacaoField;

        private string fpasField;

        private string codTercsField;

        private string codTercsSuspField;

        private eSocialEvtCSInfoCSIdeEstabIdeLotacaoInfoTercSusp[] infoTercSuspField;

        private eSocialEvtCSInfoCSIdeEstabIdeLotacaoInfoEmprParcial infoEmprParcialField;

        private eSocialEvtCSInfoCSIdeEstabIdeLotacaoDadosOpPort dadosOpPortField;

        private eSocialEvtCSInfoCSIdeEstabIdeLotacaoBasesRemun[] basesRemunField;

        private eSocialEvtCSInfoCSIdeEstabIdeLotacaoBasesAvNPort basesAvNPortField;

        private eSocialEvtCSInfoCSIdeEstabIdeLotacaoInfoSubstPatrOpPort infoSubstPatrOpPortField;

        /// <remarks/>
        public string codLotacao
        {
            get
            {
                return this.codLotacaoField;
            }
            set
            {
                this.codLotacaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string fpas
        {
            get
            {
                return this.fpasField;
            }
            set
            {
                this.fpasField = value;
            }
        }

        /// <remarks/>
        public string codTercs
        {
            get
            {
                return this.codTercsField;
            }
            set
            {
                this.codTercsField = value;
            }
        }

        /// <remarks/>
        public string codTercsSusp
        {
            get
            {
                return this.codTercsSuspField;
            }
            set
            {
                this.codTercsSuspField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("infoTercSusp")]
        public eSocialEvtCSInfoCSIdeEstabIdeLotacaoInfoTercSusp[] infoTercSusp
        {
            get
            {
                return this.infoTercSuspField;
            }
            set
            {
                this.infoTercSuspField = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCSIdeEstabIdeLotacaoInfoEmprParcial infoEmprParcial
        {
            get
            {
                return this.infoEmprParcialField;
            }
            set
            {
                this.infoEmprParcialField = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCSIdeEstabIdeLotacaoDadosOpPort dadosOpPort
        {
            get
            {
                return this.dadosOpPortField;
            }
            set
            {
                this.dadosOpPortField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("basesRemun")]
        public eSocialEvtCSInfoCSIdeEstabIdeLotacaoBasesRemun[] basesRemun
        {
            get
            {
                return this.basesRemunField;
            }
            set
            {
                this.basesRemunField = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCSIdeEstabIdeLotacaoBasesAvNPort basesAvNPort
        {
            get
            {
                return this.basesAvNPortField;
            }
            set
            {
                this.basesAvNPortField = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCSIdeEstabIdeLotacaoInfoSubstPatrOpPort infoSubstPatrOpPort
        {
            get
            {
                return this.infoSubstPatrOpPortField;
            }
            set
            {
                this.infoSubstPatrOpPortField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstabIdeLotacaoInfoTercSusp
    {

        private string codTercField;

        /// <remarks/>
        public string codTerc
        {
            get
            {
                return this.codTercField;
            }
            set
            {
                this.codTercField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstabIdeLotacaoInfoEmprParcial
    {

        private sbyte tpInscContratField;

        private string nrInscContratField;

        private sbyte tpInscPropField;

        private string nrInscPropField;

        private string cnoObraField;

        /// <remarks/>
        public sbyte tpInscContrat
        {
            get
            {
                return this.tpInscContratField;
            }
            set
            {
                this.tpInscContratField = value;
            }
        }

        /// <remarks/>
        public string nrInscContrat
        {
            get
            {
                return this.nrInscContratField;
            }
            set
            {
                this.nrInscContratField = value;
            }
        }

        /// <remarks/>
        public sbyte tpInscProp
        {
            get
            {
                return this.tpInscPropField;
            }
            set
            {
                this.tpInscPropField = value;
            }
        }

        /// <remarks/>
        public string nrInscProp
        {
            get
            {
                return this.nrInscPropField;
            }
            set
            {
                this.nrInscPropField = value;
            }
        }

        /// <remarks/>
        public string cnoObra
        {
            get
            {
                return this.cnoObraField;
            }
            set
            {
                this.cnoObraField = value;
            }
        }
    }

    public partial class eSocialEvtCSInfoCSIdeEstabIdeLotacaoDadosOpPort
    {

        private string cnpjOpPortuarioField;

        private sbyte aliqRatField;

        private decimal fapField;

        private decimal aliqRatAjustField;

        /// <remarks/>
        public string cnpjOpPortuario
        {
            get
            {
                return this.cnpjOpPortuarioField;
            }
            set
            {
                this.cnpjOpPortuarioField = value;
            }
        }

        /// <remarks/>
        public sbyte aliqRat
        {
            get
            {
                return this.aliqRatField;
            }
            set
            {
                this.aliqRatField = value;
            }
        }

        /// <remarks/>
        public decimal fap
        {
            get
            {
                return this.fapField;
            }
            set
            {
                this.fapField = value;
            }
        }

        /// <remarks/>
        public decimal aliqRatAjust
        {
            get
            {
                return this.aliqRatAjustField;
            }
            set
            {
                this.aliqRatAjustField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstabIdeLotacaoBasesRemun
    {

        private sbyte indIncidField;

        private string codCategField;

        private eSocialEvtCSInfoCSIdeEstabIdeLotacaoBasesRemunBasesCp basesCpField;

        /// <remarks/>
        public sbyte indIncid
        {
            get
            {
                return this.indIncidField;
            }
            set
            {
                this.indIncidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string codCateg
        {
            get
            {
                return this.codCategField;
            }
            set
            {
                this.codCategField = value;
            }
        }

        /// <remarks/>
        public eSocialEvtCSInfoCSIdeEstabIdeLotacaoBasesRemunBasesCp basesCp
        {
            get
            {
                return this.basesCpField;
            }
            set
            {
                this.basesCpField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstabIdeLotacaoBasesRemunBasesCp
    {

        private decimal vrBcCp00Field;

        private decimal vrBcCp15Field;

        private decimal vrBcCp20Field;

        private decimal vrBcCp25Field;

        private decimal vrSuspBcCp00Field;

        private decimal vrSuspBcCp15Field;

        private decimal vrSuspBcCp20Field;

        private decimal vrSuspBcCp25Field;

        private decimal vrBcCp00VAField;

        private bool vrBcCp00VAFieldSpecified;

        private decimal vrBcCp15VAField;

        private bool vrBcCp15VAFieldSpecified;

        private decimal vrBcCp20VAField;

        private bool vrBcCp20VAFieldSpecified;

        private decimal vrBcCp25VAField;

        private bool vrBcCp25VAFieldSpecified;

        private decimal vrSuspBcCp00VAField;

        private bool vrSuspBcCp00VAFieldSpecified;

        private decimal vrSuspBcCp15VAField;

        private bool vrSuspBcCp15VAFieldSpecified;

        private decimal vrSuspBcCp20VAField;

        private bool vrSuspBcCp20VAFieldSpecified;

        private decimal vrSuspBcCp25VAField;

        private bool vrSuspBcCp25VAFieldSpecified;

        private decimal vrDescSestField;

        private decimal vrCalcSestField;

        private decimal vrDescSenatField;

        private decimal vrCalcSenatField;

        private decimal vrSalFamField;

        private decimal vrSalMatField;

        /// <remarks/>
        public decimal vrBcCp00
        {
            get
            {
                return this.vrBcCp00Field;
            }
            set
            {
                this.vrBcCp00Field = value;
            }
        }

        /// <remarks/>
        public decimal vrBcCp15
        {
            get
            {
                return this.vrBcCp15Field;
            }
            set
            {
                this.vrBcCp15Field = value;
            }
        }

        /// <remarks/>
        public decimal vrBcCp20
        {
            get
            {
                return this.vrBcCp20Field;
            }
            set
            {
                this.vrBcCp20Field = value;
            }
        }

        /// <remarks/>
        public decimal vrBcCp25
        {
            get
            {
                return this.vrBcCp25Field;
            }
            set
            {
                this.vrBcCp25Field = value;
            }
        }

        /// <remarks/>
        public decimal vrSuspBcCp00
        {
            get
            {
                return this.vrSuspBcCp00Field;
            }
            set
            {
                this.vrSuspBcCp00Field = value;
            }
        }

        /// <remarks/>
        public decimal vrSuspBcCp15
        {
            get
            {
                return this.vrSuspBcCp15Field;
            }
            set
            {
                this.vrSuspBcCp15Field = value;
            }
        }

        /// <remarks/>
        public decimal vrSuspBcCp20
        {
            get
            {
                return this.vrSuspBcCp20Field;
            }
            set
            {
                this.vrSuspBcCp20Field = value;
            }
        }

        /// <remarks/>
        public decimal vrSuspBcCp25
        {
            get
            {
                return this.vrSuspBcCp25Field;
            }
            set
            {
                this.vrSuspBcCp25Field = value;
            }
        }

        /// <remarks/>
        public decimal vrBcCp00VA
        {
            get
            {
                return this.vrBcCp00VAField;
            }
            set
            {
                this.vrBcCp00VAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrBcCp00VASpecified
        {
            get
            {
                return this.vrBcCp00VAFieldSpecified;
            }
            set
            {
                this.vrBcCp00VAFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vrBcCp15VA
        {
            get
            {
                return this.vrBcCp15VAField;
            }
            set
            {
                this.vrBcCp15VAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrBcCp15VASpecified
        {
            get
            {
                return this.vrBcCp15VAFieldSpecified;
            }
            set
            {
                this.vrBcCp15VAFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vrBcCp20VA
        {
            get
            {
                return this.vrBcCp20VAField;
            }
            set
            {
                this.vrBcCp20VAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrBcCp20VASpecified
        {
            get
            {
                return this.vrBcCp20VAFieldSpecified;
            }
            set
            {
                this.vrBcCp20VAFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vrBcCp25VA
        {
            get
            {
                return this.vrBcCp25VAField;
            }
            set
            {
                this.vrBcCp25VAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrBcCp25VASpecified
        {
            get
            {
                return this.vrBcCp25VAFieldSpecified;
            }
            set
            {
                this.vrBcCp25VAFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vrSuspBcCp00VA
        {
            get
            {
                return this.vrSuspBcCp00VAField;
            }
            set
            {
                this.vrSuspBcCp00VAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrSuspBcCp00VASpecified
        {
            get
            {
                return this.vrSuspBcCp00VAFieldSpecified;
            }
            set
            {
                this.vrSuspBcCp00VAFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vrSuspBcCp15VA
        {
            get
            {
                return this.vrSuspBcCp15VAField;
            }
            set
            {
                this.vrSuspBcCp15VAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrSuspBcCp15VASpecified
        {
            get
            {
                return this.vrSuspBcCp15VAFieldSpecified;
            }
            set
            {
                this.vrSuspBcCp15VAFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vrSuspBcCp20VA
        {
            get
            {
                return this.vrSuspBcCp20VAField;
            }
            set
            {
                this.vrSuspBcCp20VAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrSuspBcCp20VASpecified
        {
            get
            {
                return this.vrSuspBcCp20VAFieldSpecified;
            }
            set
            {
                this.vrSuspBcCp20VAFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vrSuspBcCp25VA
        {
            get
            {
                return this.vrSuspBcCp25VAField;
            }
            set
            {
                this.vrSuspBcCp25VAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrSuspBcCp25VASpecified
        {
            get
            {
                return this.vrSuspBcCp25VAFieldSpecified;
            }
            set
            {
                this.vrSuspBcCp25VAFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vrDescSest
        {
            get
            {
                return this.vrDescSestField;
            }
            set
            {
                this.vrDescSestField = value;
            }
        }

        /// <remarks/>
        public decimal vrCalcSest
        {
            get
            {
                return this.vrCalcSestField;
            }
            set
            {
                this.vrCalcSestField = value;
            }
        }

        /// <remarks/>
        public decimal vrDescSenat
        {
            get
            {
                return this.vrDescSenatField;
            }
            set
            {
                this.vrDescSenatField = value;
            }
        }

        /// <remarks/>
        public decimal vrCalcSenat
        {
            get
            {
                return this.vrCalcSenatField;
            }
            set
            {
                this.vrCalcSenatField = value;
            }
        }

        /// <remarks/>
        public decimal vrSalFam
        {
            get
            {
                return this.vrSalFamField;
            }
            set
            {
                this.vrSalFamField = value;
            }
        }

        /// <remarks/>
        public decimal vrSalMat
        {
            get
            {
                return this.vrSalMatField;
            }
            set
            {
                this.vrSalMatField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstabIdeLotacaoBasesAvNPort
    {

        private decimal vrBcCp00Field;

        private decimal vrBcCp15Field;

        private decimal vrBcCp20Field;

        private decimal vrBcCp25Field;

        private decimal vrBcCp13Field;

        private decimal vrDescCPField;

        /// <remarks/>
        public decimal vrBcCp00
        {
            get
            {
                return this.vrBcCp00Field;
            }
            set
            {
                this.vrBcCp00Field = value;
            }
        }

        /// <remarks/>
        public decimal vrBcCp15
        {
            get
            {
                return this.vrBcCp15Field;
            }
            set
            {
                this.vrBcCp15Field = value;
            }
        }

        /// <remarks/>
        public decimal vrBcCp20
        {
            get
            {
                return this.vrBcCp20Field;
            }
            set
            {
                this.vrBcCp20Field = value;
            }
        }

        /// <remarks/>
        public decimal vrBcCp25
        {
            get
            {
                return this.vrBcCp25Field;
            }
            set
            {
                this.vrBcCp25Field = value;
            }
        }

        /// <remarks/>
        public decimal vrBcCp13
        {
            get
            {
                return this.vrBcCp13Field;
            }
            set
            {
                this.vrBcCp13Field = value;
            }
        }

        /// <remarks/>
        public decimal vrDescCP
        {
            get
            {
                return this.vrDescCPField;
            }
            set
            {
                this.vrDescCPField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstabIdeLotacaoInfoSubstPatrOpPort
    {

        private string cnpjOpPortuarioField;

        /// <remarks/>
        public string cnpjOpPortuario
        {
            get
            {
                return this.cnpjOpPortuarioField;
            }
            set
            {
                this.cnpjOpPortuarioField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstabBasesAquis
    {

        private sbyte indAquisField;

        private decimal vlrAquisField;

        private decimal vrCPDescPRField;

        private decimal vrCPNRetField;

        private decimal vrRatNRetField;

        private decimal vrSenarNRetField;

        private decimal vrCPCalcPRField;

        private decimal vrRatDescPRField;

        private decimal vrRatCalcPRField;

        private decimal vrSenarDescField;

        private decimal vrSenarCalcField;

        /// <remarks/>
        public sbyte indAquis
        {
            get
            {
                return this.indAquisField;
            }
            set
            {
                this.indAquisField = value;
            }
        }

        /// <remarks/>
        public decimal vlrAquis
        {
            get
            {
                return this.vlrAquisField;
            }
            set
            {
                this.vlrAquisField = value;
            }
        }

        /// <remarks/>
        public decimal vrCPDescPR
        {
            get
            {
                return this.vrCPDescPRField;
            }
            set
            {
                this.vrCPDescPRField = value;
            }
        }

        /// <remarks/>
        public decimal vrCPNRet
        {
            get
            {
                return this.vrCPNRetField;
            }
            set
            {
                this.vrCPNRetField = value;
            }
        }

        /// <remarks/>
        public decimal vrRatNRet
        {
            get
            {
                return this.vrRatNRetField;
            }
            set
            {
                this.vrRatNRetField = value;
            }
        }

        /// <remarks/>
        public decimal vrSenarNRet
        {
            get
            {
                return this.vrSenarNRetField;
            }
            set
            {
                this.vrSenarNRetField = value;
            }
        }

        /// <remarks/>
        public decimal vrCPCalcPR
        {
            get
            {
                return this.vrCPCalcPRField;
            }
            set
            {
                this.vrCPCalcPRField = value;
            }
        }

        /// <remarks/>
        public decimal vrRatDescPR
        {
            get
            {
                return this.vrRatDescPRField;
            }
            set
            {
                this.vrRatDescPRField = value;
            }
        }

        /// <remarks/>
        public decimal vrRatCalcPR
        {
            get
            {
                return this.vrRatCalcPRField;
            }
            set
            {
                this.vrRatCalcPRField = value;
            }
        }

        /// <remarks/>
        public decimal vrSenarDesc
        {
            get
            {
                return this.vrSenarDescField;
            }
            set
            {
                this.vrSenarDescField = value;
            }
        }

        /// <remarks/>
        public decimal vrSenarCalc
        {
            get
            {
                return this.vrSenarCalcField;
            }
            set
            {
                this.vrSenarCalcField = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstabBasesComerc
    {

        private sbyte indComercField;

        private decimal vrBcComPRField;

        private decimal vrCPSuspField;

        private bool vrCPSuspFieldSpecified;

        private decimal vrRatSuspField;

        private bool vrRatSuspFieldSpecified;

        private decimal vrSenarSuspField;

        private bool vrSenarSuspFieldSpecified;

        /// <remarks/>
        public sbyte indComerc
        {
            get
            {
                return this.indComercField;
            }
            set
            {
                this.indComercField = value;
            }
        }

        /// <remarks/>
        public decimal vrBcComPR
        {
            get
            {
                return this.vrBcComPRField;
            }
            set
            {
                this.vrBcComPRField = value;
            }
        }

        /// <remarks/>
        public decimal vrCPSusp
        {
            get
            {
                return this.vrCPSuspField;
            }
            set
            {
                this.vrCPSuspField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrCPSuspSpecified
        {
            get
            {
                return this.vrCPSuspFieldSpecified;
            }
            set
            {
                this.vrCPSuspFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vrRatSusp
        {
            get
            {
                return this.vrRatSuspField;
            }
            set
            {
                this.vrRatSuspField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrRatSuspSpecified
        {
            get
            {
                return this.vrRatSuspFieldSpecified;
            }
            set
            {
                this.vrRatSuspFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal vrSenarSusp
        {
            get
            {
                return this.vrSenarSuspField;
            }
            set
            {
                this.vrSenarSuspField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrSenarSuspSpecified
        {
            get
            {
                return this.vrSenarSuspFieldSpecified;
            }
            set
            {
                this.vrSenarSuspFieldSpecified = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSIdeEstabInfoCREstab
    {

        private string tpCRField;

        private decimal vrCRField;

        private decimal vrSuspCRField;

        private bool vrSuspCRFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string tpCR
        {
            get
            {
                return this.tpCRField;
            }
            set
            {
                this.tpCRField = value;
            }
        }

        /// <remarks/>
        public decimal vrCR
        {
            get
            {
                return this.vrCRField;
            }
            set
            {
                this.vrCRField = value;
            }
        }

        /// <remarks/>
        public decimal vrSuspCR
        {
            get
            {
                return this.vrSuspCRField;
            }
            set
            {
                this.vrSuspCRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrSuspCRSpecified
        {
            get
            {
                return this.vrSuspCRFieldSpecified;
            }
            set
            {
                this.vrSuspCRFieldSpecified = value;
            }
        }
    }


    public partial class eSocialEvtCSInfoCSInfoCRContrib
    {

        private string tpCRField;

        private decimal vrCRField;

        private decimal vrCRSuspField;

        private bool vrCRSuspFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string tpCR
        {
            get
            {
                return this.tpCRField;
            }
            set
            {
                this.tpCRField = value;
            }
        }

        /// <remarks/>
        public decimal vrCR
        {
            get
            {
                return this.vrCRField;
            }
            set
            {
                this.vrCRField = value;
            }
        }

        /// <remarks/>
        public decimal vrCRSusp
        {
            get
            {
                return this.vrCRSuspField;
            }
            set
            {
                this.vrCRSuspField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrCRSuspSpecified
        {
            get
            {
                return this.vrCRSuspFieldSpecified;
            }
            set
            {
                this.vrCRSuspFieldSpecified = value;
            }
        }
    }
}