//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace BibliotecaEsocial.ClassesEsquemas.S2410
{ 

    /// <remarks/>
 [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtCdBenIn/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtCdBenIn/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtCdBenIn evtCdBenInField;
    
    /// <remarks/>
    public eSocialEvtCdBenIn evtCdBenIn {
        get {
            return this.evtCdBenInField;
        }
        set {
            this.evtCdBenInField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtCdBenIn/v_S_01_00_00")]
public partial class eSocialEvtCdBenIn {
    
    private T_ideEvento_trab_PJ ideEventoField;
    
    private T_ideEmpregador_cnpj ideEmpregadorField;
    
    private eSocialEvtCdBenInBeneficiario beneficiarioField;
    
    private eSocialEvtCdBenInInfoBenInicio infoBenInicioField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_trab_PJ ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador_cnpj ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtCdBenInBeneficiario beneficiario {
        get {
            return this.beneficiarioField;
        }
        set {
            this.beneficiarioField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtCdBenInInfoBenInicio infoBenInicio {
        get {
            return this.infoBenInicioField;
        }
        set {
            this.infoBenInicioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_trab_PJ {
    
    private sbyte indRetifField;
    
    private string nrReciboField;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indRetif {
        get {
            return this.indRetifField;
        }
        set {
            this.indRetifField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecibo {
        get {
            return this.nrReciboField;
        }
        set {
            this.nrReciboField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_ideEmpregador_cnpj {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtCdBenInBeneficiario {
    
    private string cpfBenefField;
    
    private string matriculaField;
    
    private string cnpjOrigemField;
    
    /// <remarks/>
    public string cpfBenef {
        get {
            return this.cpfBenefField;
        }
        set {
            this.cpfBenefField = value;
        }
    }
    
    /// <remarks/>
    public string matricula {
        get {
            return this.matriculaField;
        }
        set {
            this.matriculaField = value;
        }
    }
    
    /// <remarks/>
    public string cnpjOrigem {
        get {
            return this.cnpjOrigemField;
        }
        set {
            this.cnpjOrigemField = value;
        }
    }
}


public partial class eSocialEvtCdBenInInfoBenInicio {
    
    private TS_sim_nao cadIniField;
    
    private sbyte indSitBenefField;
    
    private bool indSitBenefFieldSpecified;
    
    private string nrBeneficioField;
    
    private System.DateTime dtIniBeneficioField;
    
    private System.DateTime dtPublicField;
    
    private bool dtPublicFieldSpecified;
    
    private eSocialEvtCdBenInInfoBenInicioDadosBeneficio dadosBeneficioField;
    
    private eSocialEvtCdBenInInfoBenInicioSucessaoBenef sucessaoBenefField;
    
    private eSocialEvtCdBenInInfoBenInicioMudancaCPF mudancaCPFField;
    
    private eSocialEvtCdBenInInfoBenInicioInfoBenTermino infoBenTerminoField;
    
    /// <remarks/>
    public TS_sim_nao cadIni {
        get {
            return this.cadIniField;
        }
        set {
            this.cadIniField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indSitBenef {
        get {
            return this.indSitBenefField;
        }
        set {
            this.indSitBenefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indSitBenefSpecified {
        get {
            return this.indSitBenefFieldSpecified;
        }
        set {
            this.indSitBenefFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string nrBeneficio {
        get {
            return this.nrBeneficioField;
        }
        set {
            this.nrBeneficioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtIniBeneficio {
        get {
            return this.dtIniBeneficioField;
        }
        set {
            this.dtIniBeneficioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtPublic {
        get {
            return this.dtPublicField;
        }
        set {
            this.dtPublicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dtPublicSpecified {
        get {
            return this.dtPublicFieldSpecified;
        }
        set {
            this.dtPublicFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtCdBenInInfoBenInicioDadosBeneficio dadosBeneficio {
        get {
            return this.dadosBeneficioField;
        }
        set {
            this.dadosBeneficioField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtCdBenInInfoBenInicioSucessaoBenef sucessaoBenef {
        get {
            return this.sucessaoBenefField;
        }
        set {
            this.sucessaoBenefField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtCdBenInInfoBenInicioMudancaCPF mudancaCPF {
        get {
            return this.mudancaCPFField;
        }
        set {
            this.mudancaCPFField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtCdBenInInfoBenInicioInfoBenTermino infoBenTermino {
        get {
            return this.infoBenTerminoField;
        }
        set {
            this.infoBenTerminoField = value;
        }
    }
}


public enum TS_sim_nao {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    N,
}


public partial class eSocialEvtCdBenInInfoBenInicioDadosBeneficio {
    
    private string tpBeneficioField;
    
    private sbyte tpPlanRPField;
    
    private string dscField;
    
    private TS_sim_nao indDecJudField;
    
    private bool indDecJudFieldSpecified;
    
    private eSocialEvtCdBenInInfoBenInicioDadosBeneficioInfoPenMorte infoPenMorteField;
    
    /// <remarks/>
    public string tpBeneficio {
        get {
            return this.tpBeneficioField;
        }
        set {
            this.tpBeneficioField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpPlanRP {
        get {
            return this.tpPlanRPField;
        }
        set {
            this.tpPlanRPField = value;
        }
    }
    
    /// <remarks/>
    public string dsc {
        get {
            return this.dscField;
        }
        set {
            this.dscField = value;
        }
    }
    
    /// <remarks/>
    public TS_sim_nao indDecJud {
        get {
            return this.indDecJudField;
        }
        set {
            this.indDecJudField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indDecJudSpecified {
        get {
            return this.indDecJudFieldSpecified;
        }
        set {
            this.indDecJudFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtCdBenInInfoBenInicioDadosBeneficioInfoPenMorte infoPenMorte {
        get {
            return this.infoPenMorteField;
        }
        set {
            this.infoPenMorteField = value;
        }
    }
}


public partial class eSocialEvtCdBenInInfoBenInicioDadosBeneficioInfoPenMorte {
    
    private sbyte tpPenMorteField;
    
    private eSocialEvtCdBenInInfoBenInicioDadosBeneficioInfoPenMorteInstPenMorte instPenMorteField;
    
    /// <remarks/>
    public sbyte tpPenMorte {
        get {
            return this.tpPenMorteField;
        }
        set {
            this.tpPenMorteField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtCdBenInInfoBenInicioDadosBeneficioInfoPenMorteInstPenMorte instPenMorte {
        get {
            return this.instPenMorteField;
        }
        set {
            this.instPenMorteField = value;
        }
    }
}


public partial class eSocialEvtCdBenInInfoBenInicioDadosBeneficioInfoPenMorteInstPenMorte {
    
    private string cpfInstField;
    
    private System.DateTime dtInstField;
    
    /// <remarks/>
    public string cpfInst {
        get {
            return this.cpfInstField;
        }
        set {
            this.cpfInstField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtInst {
        get {
            return this.dtInstField;
        }
        set {
            this.dtInstField = value;
        }
    }
}


public partial class eSocialEvtCdBenInInfoBenInicioSucessaoBenef {
    
    private string cnpjOrgaoAntField;
    
    private string nrBeneficioAntField;
    
    private System.DateTime dtTransfField;
    
    private string observacaoField;
    
    /// <remarks/>
    public string cnpjOrgaoAnt {
        get {
            return this.cnpjOrgaoAntField;
        }
        set {
            this.cnpjOrgaoAntField = value;
        }
    }
    
    /// <remarks/>
    public string nrBeneficioAnt {
        get {
            return this.nrBeneficioAntField;
        }
        set {
            this.nrBeneficioAntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtTransf {
        get {
            return this.dtTransfField;
        }
        set {
            this.dtTransfField = value;
        }
    }
    
    /// <remarks/>
    public string observacao {
        get {
            return this.observacaoField;
        }
        set {
            this.observacaoField = value;
        }
    }
}


public partial class eSocialEvtCdBenInInfoBenInicioMudancaCPF {
    
    private string cpfAntField;
    
    private string nrBeneficioAntField;
    
    private System.DateTime dtAltCPFField;
    
    private string observacaoField;
    
    /// <remarks/>
    public string cpfAnt {
        get {
            return this.cpfAntField;
        }
        set {
            this.cpfAntField = value;
        }
    }
    
    /// <remarks/>
    public string nrBeneficioAnt {
        get {
            return this.nrBeneficioAntField;
        }
        set {
            this.nrBeneficioAntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtAltCPF {
        get {
            return this.dtAltCPFField;
        }
        set {
            this.dtAltCPFField = value;
        }
    }
    
    /// <remarks/>
    public string observacao {
        get {
            return this.observacaoField;
        }
        set {
            this.observacaoField = value;
        }
    }
}


public partial class eSocialEvtCdBenInInfoBenInicioInfoBenTermino {
    
    private System.DateTime dtTermBeneficioField;
    
    private string mtvTerminoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtTermBeneficio {
        get {
            return this.dtTermBeneficioField;
        }
        set {
            this.dtTermBeneficioField = value;
        }
    }
    
    /// <remarks/>
    public string mtvTermino {
        get {
            return this.mtvTerminoField;
        }
        set {
            this.mtvTerminoField = value;
        }
    }
}
}