//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace BibliotecaEsocial.Model.S1260
{ 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtComProd/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtComProd/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtComProd evtComProdField;
    
    /// <remarks/>
    public eSocialEvtComProd evtComProd {
        get {
            return this.evtComProdField;
        }
        set {
            this.evtComProdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtComProd/v_S_01_00_00")]
public partial class eSocialEvtComProd {
    
    private T_ideEvento_folha_mensal_PF ideEventoField;
    
    private eSocialEvtComProdIdeEmpregador ideEmpregadorField;
    
    private eSocialEvtComProdInfoComProd infoComProdField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_folha_mensal_PF ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtComProdIdeEmpregador ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtComProdInfoComProd infoComProd {
        get {
            return this.infoComProdField;
        }
        set {
            this.infoComProdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_folha_mensal_PF {
    
    private sbyte indRetifField;
    
    private string nrReciboField;
    
    private string perApurField;
    
    private sbyte indGuiaField;
    
    private bool indGuiaFieldSpecified;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indRetif {
        get {
            return this.indRetifField;
        }
        set {
            this.indRetifField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecibo {
        get {
            return this.nrReciboField;
        }
        set {
            this.nrReciboField = value;
        }
    }
    
    /// <remarks/>
    public string perApur {
        get {
            return this.perApurField;
        }
        set {
            this.perApurField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indGuia {
        get {
            return this.indGuiaField;
        }
        set {
            this.indGuiaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indGuiaSpecified {
        get {
            return this.indGuiaFieldSpecified;
        }
        set {
            this.indGuiaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class eSocialEvtComProdIdeEmpregador {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtComProdInfoComProd {
    
    private eSocialEvtComProdInfoComProdIdeEstabel ideEstabelField;
    
    /// <remarks/>
    public eSocialEvtComProdInfoComProdIdeEstabel ideEstabel {
        get {
            return this.ideEstabelField;
        }
        set {
            this.ideEstabelField = value;
        }
    }
}


public partial class eSocialEvtComProdInfoComProdIdeEstabel {
    
    private string nrInscEstabRuralField;
    
    private eSocialEvtComProdInfoComProdIdeEstabelTpComerc[] tpComercField;
    
    /// <remarks/>
    public string nrInscEstabRural {
        get {
            return this.nrInscEstabRuralField;
        }
        set {
            this.nrInscEstabRuralField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tpComerc")]
    public eSocialEvtComProdInfoComProdIdeEstabelTpComerc[] tpComerc {
        get {
            return this.tpComercField;
        }
        set {
            this.tpComercField = value;
        }
    }
}


public partial class eSocialEvtComProdInfoComProdIdeEstabelTpComerc {
    
    private sbyte indComercField;
    
    private decimal vrTotComField;
    
    private eSocialEvtComProdInfoComProdIdeEstabelTpComercIdeAdquir[] ideAdquirField;
    
    private eSocialEvtComProdInfoComProdIdeEstabelTpComercInfoProcJud[] infoProcJudField;
    
    /// <remarks/>
    public sbyte indComerc {
        get {
            return this.indComercField;
        }
        set {
            this.indComercField = value;
        }
    }
    
    /// <remarks/>
    public decimal vrTotCom {
        get {
            return this.vrTotComField;
        }
        set {
            this.vrTotComField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ideAdquir")]
    public eSocialEvtComProdInfoComProdIdeEstabelTpComercIdeAdquir[] ideAdquir {
        get {
            return this.ideAdquirField;
        }
        set {
            this.ideAdquirField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("infoProcJud")]
    public eSocialEvtComProdInfoComProdIdeEstabelTpComercInfoProcJud[] infoProcJud {
        get {
            return this.infoProcJudField;
        }
        set {
            this.infoProcJudField = value;
        }
    }
}


public partial class eSocialEvtComProdInfoComProdIdeEstabelTpComercIdeAdquir {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    private decimal vrComercField;
    
    private eSocialEvtComProdInfoComProdIdeEstabelTpComercIdeAdquirNfs[] nfsField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
    
    /// <remarks/>
    public decimal vrComerc {
        get {
            return this.vrComercField;
        }
        set {
            this.vrComercField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("nfs")]
    public eSocialEvtComProdInfoComProdIdeEstabelTpComercIdeAdquirNfs[] nfs {
        get {
            return this.nfsField;
        }
        set {
            this.nfsField = value;
        }
    }
}


public partial class eSocialEvtComProdInfoComProdIdeEstabelTpComercIdeAdquirNfs {
    
    private string serieField;
    
    private string nrDoctoField;
    
    private System.DateTime dtEmisNFField;
    
    private decimal vlrBrutoField;
    
    private decimal vrCPDescPRField;
    
    private decimal vrRatDescPRField;
    
    private decimal vrSenarDescField;
    
    /// <remarks/>
    public string serie {
        get {
            return this.serieField;
        }
        set {
            this.serieField = value;
        }
    }
    
    /// <remarks/>
    public string nrDocto {
        get {
            return this.nrDoctoField;
        }
        set {
            this.nrDoctoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtEmisNF {
        get {
            return this.dtEmisNFField;
        }
        set {
            this.dtEmisNFField = value;
        }
    }
    
    /// <remarks/>
    public decimal vlrBruto {
        get {
            return this.vlrBrutoField;
        }
        set {
            this.vlrBrutoField = value;
        }
    }
    
    /// <remarks/>
    public decimal vrCPDescPR {
        get {
            return this.vrCPDescPRField;
        }
        set {
            this.vrCPDescPRField = value;
        }
    }
    
    /// <remarks/>
    public decimal vrRatDescPR {
        get {
            return this.vrRatDescPRField;
        }
        set {
            this.vrRatDescPRField = value;
        }
    }
    
    /// <remarks/>
    public decimal vrSenarDesc {
        get {
            return this.vrSenarDescField;
        }
        set {
            this.vrSenarDescField = value;
        }
    }
}


public partial class eSocialEvtComProdInfoComProdIdeEstabelTpComercInfoProcJud {
    
    private sbyte tpProcField;
    
    private string nrProcField;
    
    private string codSuspField;
    
    private decimal vrCPSuspField;
    
    private bool vrCPSuspFieldSpecified;
    
    private decimal vrRatSuspField;
    
    private bool vrRatSuspFieldSpecified;
    
    private decimal vrSenarSuspField;
    
    private bool vrSenarSuspFieldSpecified;
    
    /// <remarks/>
    public sbyte tpProc {
        get {
            return this.tpProcField;
        }
        set {
            this.tpProcField = value;
        }
    }
    
    /// <remarks/>
    public string nrProc {
        get {
            return this.nrProcField;
        }
        set {
            this.nrProcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codSusp {
        get {
            return this.codSuspField;
        }
        set {
            this.codSuspField = value;
        }
    }
    
    /// <remarks/>
    public decimal vrCPSusp {
        get {
            return this.vrCPSuspField;
        }
        set {
            this.vrCPSuspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vrCPSuspSpecified {
        get {
            return this.vrCPSuspFieldSpecified;
        }
        set {
            this.vrCPSuspFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal vrRatSusp {
        get {
            return this.vrRatSuspField;
        }
        set {
            this.vrRatSuspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vrRatSuspSpecified {
        get {
            return this.vrRatSuspFieldSpecified;
        }
        set {
            this.vrRatSuspFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal vrSenarSusp {
        get {
            return this.vrSenarSuspField;
        }
        set {
            this.vrSenarSuspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vrSenarSuspSpecified {
        get {
            return this.vrSenarSuspFieldSpecified;
        }
        set {
            this.vrSenarSuspFieldSpecified = value;
        }
    }
}
}