//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace BibliotecaEsocial.Model.S2416 
{

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtCdBenAlt/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtCdBenAlt/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtCdBenAlt evtCdBenAltField;
    
    /// <remarks/>
    public eSocialEvtCdBenAlt evtCdBenAlt {
        get {
            return this.evtCdBenAltField;
        }
        set {
            this.evtCdBenAltField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtCdBenAlt/v_S_01_00_00")]
public partial class eSocialEvtCdBenAlt {
    
    private T_ideEvento_trab_PJ ideEventoField;
    
    private T_ideEmpregador_cnpj ideEmpregadorField;
    
    private T_ideBeneficio ideBeneficioField;
    
    private eSocialEvtCdBenAltInfoBenAlteracao infoBenAlteracaoField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_trab_PJ ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador_cnpj ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public T_ideBeneficio ideBeneficio {
        get {
            return this.ideBeneficioField;
        }
        set {
            this.ideBeneficioField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtCdBenAltInfoBenAlteracao infoBenAlteracao {
        get {
            return this.infoBenAlteracaoField;
        }
        set {
            this.infoBenAlteracaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_trab_PJ {
    
    private sbyte indRetifField;
    
    private string nrReciboField;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indRetif {
        get {
            return this.indRetifField;
        }
        set {
            this.indRetifField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecibo {
        get {
            return this.nrReciboField;
        }
        set {
            this.nrReciboField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_ideBeneficio {
    
    private string cpfBenefField;
    
    private string nrBeneficioField;
    
    /// <remarks/>
    public string cpfBenef {
        get {
            return this.cpfBenefField;
        }
        set {
            this.cpfBenefField = value;
        }
    }
    
    /// <remarks/>
    public string nrBeneficio {
        get {
            return this.nrBeneficioField;
        }
        set {
            this.nrBeneficioField = value;
        }
    }
}


public partial class T_ideEmpregador_cnpj {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtCdBenAltInfoBenAlteracao {
    
    private System.DateTime dtAltBeneficioField;
    
    private eSocialEvtCdBenAltInfoBenAlteracaoDadosBeneficio dadosBeneficioField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtAltBeneficio {
        get {
            return this.dtAltBeneficioField;
        }
        set {
            this.dtAltBeneficioField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtCdBenAltInfoBenAlteracaoDadosBeneficio dadosBeneficio {
        get {
            return this.dadosBeneficioField;
        }
        set {
            this.dadosBeneficioField = value;
        }
    }
}


public partial class eSocialEvtCdBenAltInfoBenAlteracaoDadosBeneficio {
    
    private string tpBeneficioField;
    
    private sbyte tpPlanRPField;
    
    private string dscField;
    
    private TS_sim_nao indSuspensaoField;
    
    private eSocialEvtCdBenAltInfoBenAlteracaoDadosBeneficioInfoPenMorte infoPenMorteField;
    
    private eSocialEvtCdBenAltInfoBenAlteracaoDadosBeneficioSuspensao suspensaoField;
    
    /// <remarks/>
    public string tpBeneficio {
        get {
            return this.tpBeneficioField;
        }
        set {
            this.tpBeneficioField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpPlanRP {
        get {
            return this.tpPlanRPField;
        }
        set {
            this.tpPlanRPField = value;
        }
    }
    
    /// <remarks/>
    public string dsc {
        get {
            return this.dscField;
        }
        set {
            this.dscField = value;
        }
    }
    
    /// <remarks/>
    public TS_sim_nao indSuspensao {
        get {
            return this.indSuspensaoField;
        }
        set {
            this.indSuspensaoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtCdBenAltInfoBenAlteracaoDadosBeneficioInfoPenMorte infoPenMorte {
        get {
            return this.infoPenMorteField;
        }
        set {
            this.infoPenMorteField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtCdBenAltInfoBenAlteracaoDadosBeneficioSuspensao suspensao {
        get {
            return this.suspensaoField;
        }
        set {
            this.suspensaoField = value;
        }
    }
}


public enum TS_sim_nao {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    N,
}


public partial class eSocialEvtCdBenAltInfoBenAlteracaoDadosBeneficioInfoPenMorte {
    
    private sbyte tpPenMorteField;
    
    /// <remarks/>
    public sbyte tpPenMorte {
        get {
            return this.tpPenMorteField;
        }
        set {
            this.tpPenMorteField = value;
        }
    }
}


public partial class eSocialEvtCdBenAltInfoBenAlteracaoDadosBeneficioSuspensao {
    
    private eSocialEvtCdBenAltInfoBenAlteracaoDadosBeneficioSuspensaoMtvSuspensao mtvSuspensaoField;
    
    private string dscSuspensaoField;
    
    /// <remarks/>
    public eSocialEvtCdBenAltInfoBenAlteracaoDadosBeneficioSuspensaoMtvSuspensao mtvSuspensao {
        get {
            return this.mtvSuspensaoField;
        }
        set {
            this.mtvSuspensaoField = value;
        }
    }
    
    /// <remarks/>
    public string dscSuspensao {
        get {
            return this.dscSuspensaoField;
        }
        set {
            this.dscSuspensaoField = value;
        }
    }
}


public enum eSocialEvtCdBenAltInfoBenAlteracaoDadosBeneficioSuspensaoMtvSuspensao {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("01")]
    Item01,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("99")]
    Item99,
}
}