//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 

namespace BibliotecaEsocial.Model.S3500 
{
    

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtExcProcTrab evtExcProcTrabField;
    
    /// <remarks/>
    public eSocialEvtExcProcTrab evtExcProcTrab {
        get {
            return this.evtExcProcTrabField;
        }
        set {
            this.evtExcProcTrabField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtExcProcTrab/v_S_01_01_00")]
public partial class eSocialEvtExcProcTrab {
    
    private T_ideEvento_exclusao_proc_trab ideEventoField;
    
    private T_ideEmpregador_exclusao ideEmpregadorField;
    
    private eSocialEvtExcProcTrabInfoExclusao infoExclusaoField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_exclusao_proc_trab ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador_exclusao ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtExcProcTrabInfoExclusao infoExclusao {
        get {
            return this.infoExclusaoField;
        }
        set {
            this.infoExclusaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_exclusao_proc_trab {
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}

public partial class T_ideEmpregador_exclusao {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtExcProcTrabInfoExclusao {
    
    private string tpEventoField;
    
    private string nrRecEvtField;
    
    private eSocialEvtExcProcTrabInfoExclusaoIdeProcTrab ideProcTrabField;
    
    /// <remarks/>
    public string tpEvento {
        get {
            return this.tpEventoField;
        }
        set {
            this.tpEventoField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecEvt {
        get {
            return this.nrRecEvtField;
        }
        set {
            this.nrRecEvtField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtExcProcTrabInfoExclusaoIdeProcTrab ideProcTrab {
        get {
            return this.ideProcTrabField;
        }
        set {
            this.ideProcTrabField = value;
        }
    }
}


public partial class eSocialEvtExcProcTrabInfoExclusaoIdeProcTrab {
    
    private string nrProcTrabField;
    
    private string cpfTrabField;
    
    private string perApurPgtoField;
    
    /// <remarks/>
    public string nrProcTrab {
        get {
            return this.nrProcTrabField;
        }
        set {
            this.nrProcTrabField = value;
        }
    }
    
    /// <remarks/>
    public string cpfTrab {
        get {
            return this.cpfTrabField;
        }
        set {
            this.cpfTrabField = value;
        }
    }
    
    /// <remarks/>
    public string perApurPgto {
        get {
            return this.perApurPgtoField;
        }
        set {
            this.perApurPgtoField = value;
        }
    }
}


}