//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace BibliotecaEsocial.Model.S1280
{


/// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtInfoComplPer/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtInfoComplPer/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtInfoComplPer evtInfoComplPerField;
    
    /// <remarks/>
    public eSocialEvtInfoComplPer evtInfoComplPer {
        get {
            return this.evtInfoComplPerField;
        }
        set {
            this.evtInfoComplPerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtInfoComplPer/v_S_01_00_00")]
public partial class eSocialEvtInfoComplPer {
    
    private T_ideEvento_folha ideEventoField;
    
    private T_ideEmpregador ideEmpregadorField;
    
    private eSocialEvtInfoComplPerInfoSubstPatr infoSubstPatrField;
    
    private eSocialEvtInfoComplPerInfoSubstPatrOpPort[] infoSubstPatrOpPortField;
    
    private eSocialEvtInfoComplPerInfoAtivConcom infoAtivConcomField;
    
    private eSocialEvtInfoComplPerInfoPercTransf11096 infoPercTransf11096Field;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_folha ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtInfoComplPerInfoSubstPatr infoSubstPatr {
        get {
            return this.infoSubstPatrField;
        }
        set {
            this.infoSubstPatrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("infoSubstPatrOpPort")]
    public eSocialEvtInfoComplPerInfoSubstPatrOpPort[] infoSubstPatrOpPort {
        get {
            return this.infoSubstPatrOpPortField;
        }
        set {
            this.infoSubstPatrOpPortField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtInfoComplPerInfoAtivConcom infoAtivConcom {
        get {
            return this.infoAtivConcomField;
        }
        set {
            this.infoAtivConcomField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtInfoComplPerInfoPercTransf11096 infoPercTransf11096 {
        get {
            return this.infoPercTransf11096Field;
        }
        set {
            this.infoPercTransf11096Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}



public partial class T_ideEvento_folha {
    
    private sbyte indRetifField;
    
    private string nrReciboField;
    
    private sbyte indApuracaoField;
    
    private string perApurField;
    
    private sbyte indGuiaField;
    
    private bool indGuiaFieldSpecified;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indRetif {
        get {
            return this.indRetifField;
        }
        set {
            this.indRetifField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecibo {
        get {
            return this.nrReciboField;
        }
        set {
            this.nrReciboField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indApuracao {
        get {
            return this.indApuracaoField;
        }
        set {
            this.indApuracaoField = value;
        }
    }
    
    /// <remarks/>
    public string perApur {
        get {
            return this.perApurField;
        }
        set {
            this.perApurField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indGuia {
        get {
            return this.indGuiaField;
        }
        set {
            this.indGuiaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indGuiaSpecified {
        get {
            return this.indGuiaFieldSpecified;
        }
        set {
            this.indGuiaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_ideEmpregador {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtInfoComplPerInfoSubstPatr {
    
    private sbyte indSubstPatrField;
    
    private decimal percRedContribField;
    
    /// <remarks/>
    public sbyte indSubstPatr {
        get {
            return this.indSubstPatrField;
        }
        set {
            this.indSubstPatrField = value;
        }
    }
    
    /// <remarks/>
    public decimal percRedContrib {
        get {
            return this.percRedContribField;
        }
        set {
            this.percRedContribField = value;
        }
    }
}


public partial class eSocialEvtInfoComplPerInfoSubstPatrOpPort {
    
    private string codLotacaoField;
    
    /// <remarks/>
    public string codLotacao {
        get {
            return this.codLotacaoField;
        }
        set {
            this.codLotacaoField = value;
        }
    }
}


public partial class eSocialEvtInfoComplPerInfoAtivConcom {
    
    private decimal fatorMesField;
    
    private decimal fator13Field;
    
    /// <remarks/>
    public decimal fatorMes {
        get {
            return this.fatorMesField;
        }
        set {
            this.fatorMesField = value;
        }
    }
    
    /// <remarks/>
    public decimal fator13 {
        get {
            return this.fator13Field;
        }
        set {
            this.fator13Field = value;
        }
    }
}


public partial class eSocialEvtInfoComplPerInfoPercTransf11096 {
    
    private sbyte percTransfField;
    
    /// <remarks/>
    public sbyte percTransf {
        get {
            return this.percTransfField;
        }
        set {
            this.percTransfField = value;
        }
    }
}
}