//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 

namespace BibliotecaEsocial.Eventos.5012 
{

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtIrrf/v_S_01_01_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtIrrf/v_S_01_01_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtIrrf evtIrrfField;
    
    /// <remarks/>
    public eSocialEvtIrrf evtIrrf {
        get {
            return this.evtIrrfField;
        }
        set {
            this.evtIrrfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtIrrf/v_S_01_01_00")]
public partial class eSocialEvtIrrf {
    
    private T_ideEvento_retorno_mensal ideEventoField;
    
    private T_ideEmpregador ideEmpregadorField;
    
    private eSocialEvtIrrfInfoIRRF infoIRRFField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_retorno_mensal ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtIrrfInfoIRRF infoIRRF {
        get {
            return this.infoIRRFField;
        }
        set {
            this.infoIRRFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_retorno_mensal {
    
    private string perApurField;
    
    /// <remarks/>
    public string perApur {
        get {
            return this.perApurField;
        }
        set {
            this.perApurField = value;
        }
    }
}


public partial class T_ideEmpregador {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtIrrfInfoIRRF {
    
    private string nrRecArqBaseField;
    
    private sbyte indExistInfoField;
    
    private eSocialEvtIrrfInfoIRRFInfoCRMen[] infoCRMenField;
    
    private eSocialEvtIrrfInfoIRRFInfoCRDia[] infoCRDiaField;
    
    /// <remarks/>
    public string nrRecArqBase {
        get {
            return this.nrRecArqBaseField;
        }
        set {
            this.nrRecArqBaseField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indExistInfo {
        get {
            return this.indExistInfoField;
        }
        set {
            this.indExistInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("infoCRMen")]
    public eSocialEvtIrrfInfoIRRFInfoCRMen[] infoCRMen {
        get {
            return this.infoCRMenField;
        }
        set {
            this.infoCRMenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("infoCRDia")]
    public eSocialEvtIrrfInfoIRRFInfoCRDia[] infoCRDia {
        get {
            return this.infoCRDiaField;
        }
        set {
            this.infoCRDiaField = value;
        }
    }
}


public partial class eSocialEvtIrrfInfoIRRFInfoCRMen {
    
    private TS_CRMen cRMenField;
    
    private decimal vrCRMenField;
    
    private decimal vrCRMenSuspField;
    
    private bool vrCRMenSuspFieldSpecified;
    
    /// <remarks/>
    public TS_CRMen CRMen {
        get {
            return this.cRMenField;
        }
        set {
            this.cRMenField = value;
        }
    }
    
    /// <remarks/>
    public decimal vrCRMen {
        get {
            return this.vrCRMenField;
        }
        set {
            this.vrCRMenField = value;
        }
    }
    
    /// <remarks/>
    public decimal vrCRMenSusp {
        get {
            return this.vrCRMenSuspField;
        }
        set {
            this.vrCRMenSuspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vrCRMenSuspSpecified {
        get {
            return this.vrCRMenSuspFieldSpecified;
        }
        set {
            this.vrCRMenSuspFieldSpecified = value;
        }
    }
}


public enum TS_CRMen {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("056107")]
    Item056107,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("056108")]
    Item056108,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("056109")]
    Item056109,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("056110")]
    Item056110,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("056111")]
    Item056111,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("056112")]
    Item056112,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("056113")]
    Item056113,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("058806")]
    Item058806,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("061001")]
    Item061001,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("353301")]
    Item353301,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("356201")]
    Item356201,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("188901")]
    Item188901,
}


public partial class eSocialEvtIrrfInfoIRRFInfoCRDia {
    
    private sbyte perApurDiaField;
    
    private TS_CRDia cRDiaField;
    
    private decimal vrCRDiaField;
    
    private decimal vrCRDiaSuspField;
    
    private bool vrCRDiaSuspFieldSpecified;
    
    /// <remarks/>
    public sbyte perApurDia {
        get {
            return this.perApurDiaField;
        }
        set {
            this.perApurDiaField = value;
        }
    }
    
    /// <remarks/>
    public TS_CRDia CRDia {
        get {
            return this.cRDiaField;
        }
        set {
            this.cRDiaField = value;
        }
    }
    
    /// <remarks/>
    public decimal vrCRDia {
        get {
            return this.vrCRDiaField;
        }
        set {
            this.vrCRDiaField = value;
        }
    }
    
    /// <remarks/>
    public decimal vrCRDiaSusp {
        get {
            return this.vrCRDiaSuspField;
        }
        set {
            this.vrCRDiaSuspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vrCRDiaSuspSpecified {
        get {
            return this.vrCRDiaSuspFieldSpecified;
        }
        set {
            this.vrCRDiaSuspFieldSpecified = value;
        }
    }
}


public enum TS_CRDia {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("047301")]
    Item047301,
}
}