//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace BibliotecaEsocial.Model.S1210
{
    

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtPgtos/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtPgtos/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtPgtos evtPgtosField;
    
    /// <remarks/>
    public eSocialEvtPgtos evtPgtos {
        get {
            return this.evtPgtosField;
        }
        set {
            this.evtPgtosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtPgtos/v_S_01_00_00")]
public partial class eSocialEvtPgtos {
    
    private T_ideEvento_folha_mensal ideEventoField;
    
    private T_ideEmpregador ideEmpregadorField;
    
    private eSocialEvtPgtosIdeBenef ideBenefField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_folha_mensal ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtPgtosIdeBenef ideBenef {
        get {
            return this.ideBenefField;
        }
        set {
            this.ideBenefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_folha_mensal {
    
    private sbyte indRetifField;
    
    private string nrReciboField;
    
    private string perApurField;
    
    private sbyte indGuiaField;
    
    private bool indGuiaFieldSpecified;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indRetif {
        get {
            return this.indRetifField;
        }
        set {
            this.indRetifField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecibo {
        get {
            return this.nrReciboField;
        }
        set {
            this.nrReciboField = value;
        }
    }
    
    /// <remarks/>
    public string perApur {
        get {
            return this.perApurField;
        }
        set {
            this.perApurField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indGuia {
        get {
            return this.indGuiaField;
        }
        set {
            this.indGuiaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indGuiaSpecified {
        get {
            return this.indGuiaFieldSpecified;
        }
        set {
            this.indGuiaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_ideEmpregador {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtPgtosIdeBenef {
    
    private string cpfBenefField;
    
    private eSocialEvtPgtosIdeBenefInfoPgto[] infoPgtoField;
    
    /// <remarks/>
    public string cpfBenef {
        get {
            return this.cpfBenefField;
        }
        set {
            this.cpfBenefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("infoPgto")]
    public eSocialEvtPgtosIdeBenefInfoPgto[] infoPgto {
        get {
            return this.infoPgtoField;
        }
        set {
            this.infoPgtoField = value;
        }
    }
}

public partial class eSocialEvtPgtosIdeBenefInfoPgto {
    
    private System.DateTime dtPgtoField;
    
    private sbyte tpPgtoField;
    
    private string perRefField;
    
    private string ideDmDevField;
    
    private decimal vrLiqField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtPgto {
        get {
            return this.dtPgtoField;
        }
        set {
            this.dtPgtoField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpPgto {
        get {
            return this.tpPgtoField;
        }
        set {
            this.tpPgtoField = value;
        }
    }
    
    /// <remarks/>
    public string perRef {
        get {
            return this.perRefField;
        }
        set {
            this.perRefField = value;
        }
    }
    
    /// <remarks/>
    public string ideDmDev {
        get {
            return this.ideDmDevField;
        }
        set {
            this.ideDmDevField = value;
        }
    }
    
    /// <remarks/>
    public decimal vrLiq {
        get {
            return this.vrLiqField;
        }
        set {
            this.vrLiqField = value;
        }
    }
}
}