//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------


using BibliotecaEsocial.Model.S1202;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace BibliotecaEsocial.Model.S1202
{


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtRmnRPPS/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtRmnRPPS/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtRmnRPPS evtRmnRPPSField;
    
    /// <remarks/>
    public eSocialEvtRmnRPPS evtRmnRPPS {
        get {
            return this.evtRmnRPPSField;
        }
        set {
            this.evtRmnRPPSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtRmnRPPS/v_S_01_00_00")]
public partial class eSocialEvtRmnRPPS {
    
    private T_ideEvento_folha_opp ideEventoField;
    
    private T_ideEmpregador_cnpj ideEmpregadorField;
    
    private eSocialEvtRmnRPPSIdeTrabalhador ideTrabalhadorField;
    
    private eSocialEvtRmnRPPSDmDev[] dmDevField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_folha_opp ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador_cnpj ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtRmnRPPSIdeTrabalhador ideTrabalhador {
        get {
            return this.ideTrabalhadorField;
        }
        set {
            this.ideTrabalhadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dmDev")]
    public eSocialEvtRmnRPPSDmDev[] dmDev {
        get {
            return this.dmDevField;
        }
        set {
            this.dmDevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_folha_opp {
    
    private sbyte indRetifField;
    
    private string nrReciboField;
    
    private sbyte indApuracaoField;
    
    private string perApurField;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indRetif {
        get {
            return this.indRetifField;
        }
        set {
            this.indRetifField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecibo {
        get {
            return this.nrReciboField;
        }
        set {
            this.nrReciboField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indApuracao {
        get {
            return this.indApuracaoField;
        }
        set {
            this.indApuracaoField = value;
        }
    }
    
    /// <remarks/>
    public string perApur {
        get {
            return this.perApurField;
        }
        set {
            this.perApurField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_itensRemun_rpps {
    
    private string codRubrField;
    
    private string ideTabRubrField;
    
    private decimal qtdRubrField;
    
    private bool qtdRubrFieldSpecified;
    
    private decimal fatorRubrField;
    
    private bool fatorRubrFieldSpecified;
    
    private decimal vrRubrField;
    
    private sbyte indApurIRField;
    
    /// <remarks/>
    public string codRubr {
        get {
            return this.codRubrField;
        }
        set {
            this.codRubrField = value;
        }
    }
    
    /// <remarks/>
    public string ideTabRubr {
        get {
            return this.ideTabRubrField;
        }
        set {
            this.ideTabRubrField = value;
        }
    }
    
    /// <remarks/>
    public decimal qtdRubr {
        get {
            return this.qtdRubrField;
        }
        set {
            this.qtdRubrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool qtdRubrSpecified {
        get {
            return this.qtdRubrFieldSpecified;
        }
        set {
            this.qtdRubrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal fatorRubr {
        get {
            return this.fatorRubrField;
        }
        set {
            this.fatorRubrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fatorRubrSpecified {
        get {
            return this.fatorRubrFieldSpecified;
        }
        set {
            this.fatorRubrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal vrRubr {
        get {
            return this.vrRubrField;
        }
        set {
            this.vrRubrField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indApurIR {
        get {
            return this.indApurIRField;
        }
        set {
            this.indApurIRField = value;
        }
    }
}


public partial class T_remunPer {
    
    private string matriculaField;
    
    private T_itensRemun_rpps[] itensRemunField;
    
    /// <remarks/>
    public string matricula {
        get {
            return this.matriculaField;
        }
        set {
            this.matriculaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("itensRemun")]
    public T_itensRemun_rpps[] itensRemun {
        get {
            return this.itensRemunField;
        }
        set {
            this.itensRemunField = value;
        }
    }
}


public partial class T_ideEmpregador_cnpj {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtRmnRPPSIdeTrabalhador {
    
    private string cpfTrabField;
    
    private eSocialEvtRmnRPPSIdeTrabalhadorInfoComplem infoComplemField;
    
    /// <remarks/>
    public string cpfTrab {
        get {
            return this.cpfTrabField;
        }
        set {
            this.cpfTrabField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtRmnRPPSIdeTrabalhadorInfoComplem infoComplem {
        get {
            return this.infoComplemField;
        }
        set {
            this.infoComplemField = value;
        }
    }
}


public partial class eSocialEvtRmnRPPSIdeTrabalhadorInfoComplem {
    
    private string nmTrabField;
    
    private System.DateTime dtNasctoField;
    
    private eSocialEvtRmnRPPSIdeTrabalhadorInfoComplemSucessaoVinc sucessaoVincField;
    
    /// <remarks/>
    public string nmTrab {
        get {
            return this.nmTrabField;
        }
        set {
            this.nmTrabField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtNascto {
        get {
            return this.dtNasctoField;
        }
        set {
            this.dtNasctoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtRmnRPPSIdeTrabalhadorInfoComplemSucessaoVinc sucessaoVinc {
        get {
            return this.sucessaoVincField;
        }
        set {
            this.sucessaoVincField = value;
        }
    }
}


public partial class eSocialEvtRmnRPPSIdeTrabalhadorInfoComplemSucessaoVinc {
    
    private string cnpjOrgaoAntField;
    
    private string matricAntField;
    
    private System.DateTime dtExercicioField;
    
    private string observacaoField;
    
    /// <remarks/>
    public string cnpjOrgaoAnt {
        get {
            return this.cnpjOrgaoAntField;
        }
        set {
            this.cnpjOrgaoAntField = value;
        }
    }
    
    /// <remarks/>
    public string matricAnt {
        get {
            return this.matricAntField;
        }
        set {
            this.matricAntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtExercicio {
        get {
            return this.dtExercicioField;
        }
        set {
            this.dtExercicioField = value;
        }
    }
    
    /// <remarks/>
    public string observacao {
        get {
            return this.observacaoField;
        }
        set {
            this.observacaoField = value;
        }
    }
}


public partial class eSocialEvtRmnRPPSDmDev {
    
    private string ideDmDevField;
    
    private string codCategField;

    private T_infoRRA infoRRAField;

    private eSocialEvtRmnRPPSDmDevIdeEstab[] infoPerApurField;
    
    private eSocialEvtRmnRPPSDmDevInfoPerAnt infoPerAntField;
    
    /// <remarks/>
    public string ideDmDev {
        get {
            return this.ideDmDevField;
        }
        set {
            this.ideDmDevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codCateg {
        get {
            return this.codCategField;
        }
        set {
            this.codCategField = value;
        }
    }

    //[System.Xml.Serialization.XmlElementAttribute("infoRRA", IsNullable = false)]
        public T_infoRRA infoRRA
    {
        get
        {
            return this.infoRRAField;
        }
        set
        {
            this.infoRRAField = value;
        }
    }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ideEstab", IsNullable=false)]
    public eSocialEvtRmnRPPSDmDevIdeEstab[] infoPerApur {
        get {
            return this.infoPerApurField;
        }
        set {
            this.infoPerApurField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtRmnRPPSDmDevInfoPerAnt infoPerAnt {
        get {
            return this.infoPerAntField;
        }
        set {
            this.infoPerAntField = value;
        }
    }
}


public partial class eSocialEvtRmnRPPSDmDevIdeEstab {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    private T_remunPer[] remunPerApurField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("remunPerApur")]
    public T_remunPer[] remunPerApur {
        get {
            return this.remunPerApurField;
        }
        set {
            this.remunPerApurField = value;
        }
    }
}

public partial class T_infoRRADespProcJud
{

    private decimal vlrDespCustasField;

    private decimal vlrDespAdvogadosField;

    /// <remarks/>
    public decimal vlrDespCustas
    {
        get
        {
            return this.vlrDespCustasField;
        }
        set
        {
            this.vlrDespCustasField = value;
        }
    }

    /// <remarks/>
    public decimal vlrDespAdvogados
    {
        get
        {
            return this.vlrDespAdvogadosField;
        }
        set
        {
            this.vlrDespAdvogadosField = value;
        }
    }
}


public partial class T_infoRRAIdeAdv
{

    private sbyte tpInscField;

    private string nrInscField;

    private decimal vlrAdvField;

    private bool vlrAdvFieldSpecified;

    /// <remarks/>
    public sbyte tpInsc
    {
        get
        {
            return this.tpInscField;
        }
        set
        {
            this.tpInscField = value;
        }
    }

    /// <remarks/>
    public string nrInsc
    {
        get
        {
            return this.nrInscField;
        }
        set
        {
            this.nrInscField = value;
        }
    }

    /// <remarks/>
    public decimal vlrAdv
    {
        get
        {
            return this.vlrAdvField;
        }
        set
        {
            this.vlrAdvField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vlrAdvSpecified
    {
        get
        {
            return this.vlrAdvFieldSpecified;
        }
        set
        {
            this.vlrAdvFieldSpecified = value;
        }
    }
}


    public partial class T_infoRRA
{

    private sbyte tpProcRRAField;

    private string nrProcRRAField;

    private string descRRAField;

    private decimal qtdMesesRRAField;

    private T_infoRRADespProcJud despProcJudField;

    private T_infoRRAIdeAdv[] ideAdvField;

        /// <remarks/>
        public sbyte tpProcRRA
    {
        get
        {
            return this.tpProcRRAField;
        }
        set
        {
            this.tpProcRRAField = value;
        }
    }

    /// <remarks/>
    public string nrProcRRA
    {
        get
        {
            return this.nrProcRRAField;
        }
        set
        {
            this.nrProcRRAField = value;
        }
    }

    /// <remarks/>
    public string descRRA
    {
        get { return this.descRRAField; }
        set { this.descRRAField = value; }
    }

    public T_infoRRADespProcJud despProcJud
        {
            get
            {
                return this.despProcJudField;
            }
            set
            {
                this.despProcJudField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ideAdv")]
        public T_infoRRAIdeAdv[] ideAdv
        {
            get
            {
                return this.ideAdvField;
            }
            set
            {
                this.ideAdvField = value;
            }
        }
    }

    /// <remarks/>
    /*public decimal qtdMesesRRA
    {
        get
        {
            return this.qtdMesesRRAField;
        }
        set
        {
            this.qtdMesesRRAField = value;
        } */
    }


    public partial class eSocialEvtRmnRPPSDmDevInfoPerAnt {
    
    private TS_sim_nao remunOrgSucField;
    
    private eSocialEvtRmnRPPSDmDevInfoPerAntIdePeriodo[] idePeriodoField;
    
    /// <remarks/>
    public TS_sim_nao remunOrgSuc {
        get {
            return this.remunOrgSucField;
        }
        set {
            this.remunOrgSucField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("idePeriodo")]
    public eSocialEvtRmnRPPSDmDevInfoPerAntIdePeriodo[] idePeriodo {
        get {
            return this.idePeriodoField;
        }
        set {
            this.idePeriodoField = value;
        }
    }
}


public enum TS_sim_nao {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    N,
}


public partial class eSocialEvtRmnRPPSDmDevInfoPerAntIdePeriodo {
    
    private string perRefField;
    
    private eSocialEvtRmnRPPSDmDevInfoPerAntIdePeriodoIdeEstab[] ideEstabField;
    
    /// <remarks/>
    public string perRef {
        get {
            return this.perRefField;
        }
        set {
            this.perRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ideEstab")]
    public eSocialEvtRmnRPPSDmDevInfoPerAntIdePeriodoIdeEstab[] ideEstab {
        get {
            return this.ideEstabField;
        }
        set {
            this.ideEstabField = value;
        }
    }
}


public partial class eSocialEvtRmnRPPSDmDevInfoPerAntIdePeriodoIdeEstab {
    
    private sbyte tpInscField;
    
    private string nrInscField;

    private T_remunPer[] remunPerApurField;


    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("remunPerAnt")]
    public T_remunPer[] remunPerAnt {
        get {
            return this.remunPerApurField;
        }
        set {
            this.remunPerApurField = value;
        }
    }
}
