//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace BibliotecaEsocial.Model.S2418
{



public partial class eSocial {
    
    private eSocialEvtReativBen evtReativBenField;
    
    /// <remarks/>
    public eSocialEvtReativBen evtReativBen {
        get {
            return this.evtReativBenField;
        }
        set {
            this.evtReativBenField = value;
        }
    }
}


public partial class eSocialEvtReativBen {
    
    private T_ideEvento_trab_PJ ideEventoField;
    
    private T_ideEmpregador_cnpj ideEmpregadorField;
    
    private T_ideBeneficio ideBeneficioField;
    
    private eSocialEvtReativBenInfoReativ infoReativField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_trab_PJ ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador_cnpj ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public T_ideBeneficio ideBeneficio {
        get {
            return this.ideBeneficioField;
        }
        set {
            this.ideBeneficioField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtReativBenInfoReativ infoReativ {
        get {
            return this.infoReativField;
        }
        set {
            this.infoReativField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}



public partial class T_ideEvento_trab_PJ {
    
    private sbyte indRetifField;
    
    private string nrReciboField;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indRetif {
        get {
            return this.indRetifField;
        }
        set {
            this.indRetifField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecibo {
        get {
            return this.nrReciboField;
        }
        set {
            this.nrReciboField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_ideBeneficio {
    
    private string cpfBenefField;
    
    private string nrBeneficioField;
    
    /// <remarks/>
    public string cpfBenef {
        get {
            return this.cpfBenefField;
        }
        set {
            this.cpfBenefField = value;
        }
    }
    
    /// <remarks/>
    public string nrBeneficio {
        get {
            return this.nrBeneficioField;
        }
        set {
            this.nrBeneficioField = value;
        }
    }
}


public partial class T_ideEmpregador_cnpj {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtReativBenInfoReativ {
    
    private System.DateTime dtEfetReativField;
    
    private System.DateTime dtEfeitoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtEfetReativ {
        get {
            return this.dtEfetReativField;
        }
        set {
            this.dtEfetReativField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtEfeito {
        get {
            return this.dtEfeitoField;
        }
        set {
            this.dtEfeitoField = value;
        }
    }
}
}