//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace BibliotecaEsocial.Model.S1200
{


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtRemun/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtRemun/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtRemun evtRemunField;
    
    /// <remarks/>
    public eSocialEvtRemun evtRemun {
        get {
            return this.evtRemunField;
        }
        set {
            this.evtRemunField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtRemun/v_S_01_00_00")]
public partial class eSocialEvtRemun {
    
    private T_ideEvento_folha ideEventoField;
    
    private T_ideEmpregador ideEmpregadorField;
    
    private eSocialEvtRemunIdeTrabalhador ideTrabalhadorField;
    
    private eSocialEvtRemunDmDev[] dmDevField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_folha ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtRemunIdeTrabalhador ideTrabalhador {
        get {
            return this.ideTrabalhadorField;
        }
        set {
            this.ideTrabalhadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dmDev")]
    public eSocialEvtRemunDmDev[] dmDev {
        get {
            return this.dmDevField;
        }
        set {
            this.dmDevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_folha {
    
    private sbyte indRetifField;
    
    private string nrReciboField;
    
    private sbyte indApuracaoField;
    
    private string perApurField;
    
    private sbyte indGuiaField;
    
    private bool indGuiaFieldSpecified;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indRetif {
        get {
            return this.indRetifField;
        }
        set {
            this.indRetifField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecibo {
        get {
            return this.nrReciboField;
        }
        set {
            this.nrReciboField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indApuracao {
        get {
            return this.indApuracaoField;
        }
        set {
            this.indApuracaoField = value;
        }
    }
    
    /// <remarks/>
    public string perApur {
        get {
            return this.perApurField;
        }
        set {
            this.perApurField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indGuia {
        get {
            return this.indGuiaField;
        }
        set {
            this.indGuiaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indGuiaSpecified {
        get {
            return this.indGuiaFieldSpecified;
        }
        set {
            this.indGuiaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_infoAgNocivo {
    
    private sbyte grauExpField;
    
    /// <remarks/>
    public sbyte grauExp {
        get {
            return this.grauExpField;
        }
        set {
            this.grauExpField = value;
        }
    }
}


public partial class T_itensRemun {
    
    private string codRubrField;
    
    private string ideTabRubrField;
    
    private decimal qtdRubrField;
    
    private bool qtdRubrFieldSpecified;
    
    private decimal fatorRubrField;
    
    private bool fatorRubrFieldSpecified;
    
    private decimal vrRubrField;
    
    private sbyte indApurIRField;
    
    private bool indApurIRFieldSpecified;
    
    /// <remarks/>
    public string codRubr {
        get {
            return this.codRubrField;
        }
        set {
            this.codRubrField = value;
        }
    }
    
    /// <remarks/>
    public string ideTabRubr {
        get {
            return this.ideTabRubrField;
        }
        set {
            this.ideTabRubrField = value;
        }
    }
    
    /// <remarks/>
    public decimal qtdRubr {
        get {
            return this.qtdRubrField;
        }
        set {
            this.qtdRubrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool qtdRubrSpecified {
        get {
            return this.qtdRubrFieldSpecified;
        }
        set {
            this.qtdRubrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal fatorRubr {
        get {
            return this.fatorRubrField;
        }
        set {
            this.fatorRubrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fatorRubrSpecified {
        get {
            return this.fatorRubrFieldSpecified;
        }
        set {
            this.fatorRubrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal vrRubr {
        get {
            return this.vrRubrField;
        }
        set {
            this.vrRubrField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indApurIR {
        get {
            return this.indApurIRField;
        }
        set {
            this.indApurIRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indApurIRSpecified {
        get {
            return this.indApurIRFieldSpecified;
        }
        set {
            this.indApurIRFieldSpecified = value;
        }
    }
}


public partial class T_infoInterm {
    
    private sbyte diaField;
    
    /// <remarks/>
    public sbyte dia {
        get {
            return this.diaField;
        }
        set {
            this.diaField = value;
        }
    }
}


public partial class T_procJudTrab {
    
    private sbyte tpTribField;
    
    private string nrProcJudField;
    
    private string codSuspField;
    
    /// <remarks/>
    public sbyte tpTrib {
        get {
            return this.tpTribField;
        }
        set {
            this.tpTribField = value;
        }
    }
    
    /// <remarks/>
    public string nrProcJud {
        get {
            return this.nrProcJudField;
        }
        set {
            this.nrProcJudField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codSusp {
        get {
            return this.codSuspField;
        }
        set {
            this.codSuspField = value;
        }
    }
}


public partial class T_ideEmpregador {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtRemunIdeTrabalhador {
    
    private string cpfTrabField;
    
    private eSocialEvtRemunIdeTrabalhadorInfoMV infoMVField;
    
    private eSocialEvtRemunIdeTrabalhadorInfoComplem infoComplemField;
    
    private T_procJudTrab[] procJudTrabField;
    
    private T_infoInterm[] infoIntermField;
    
    /// <remarks/>
    public string cpfTrab {
        get {
            return this.cpfTrabField;
        }
        set {
            this.cpfTrabField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtRemunIdeTrabalhadorInfoMV infoMV {
        get {
            return this.infoMVField;
        }
        set {
            this.infoMVField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtRemunIdeTrabalhadorInfoComplem infoComplem {
        get {
            return this.infoComplemField;
        }
        set {
            this.infoComplemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("procJudTrab")]
    public T_procJudTrab[] procJudTrab {
        get {
            return this.procJudTrabField;
        }
        set {
            this.procJudTrabField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("infoInterm")]
    public T_infoInterm[] infoInterm {
        get {
            return this.infoIntermField;
        }
        set {
            this.infoIntermField = value;
        }
    }
}


public partial class eSocialEvtRemunIdeTrabalhadorInfoMV {
    
    private sbyte indMVField;
    
    private eSocialEvtRemunIdeTrabalhadorInfoMVRemunOutrEmpr[] remunOutrEmprField;
    
    /// <remarks/>
    public sbyte indMV {
        get {
            return this.indMVField;
        }
        set {
            this.indMVField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("remunOutrEmpr")]
    public eSocialEvtRemunIdeTrabalhadorInfoMVRemunOutrEmpr[] remunOutrEmpr {
        get {
            return this.remunOutrEmprField;
        }
        set {
            this.remunOutrEmprField = value;
        }
    }
}


public partial class eSocialEvtRemunIdeTrabalhadorInfoMVRemunOutrEmpr {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    private string codCategField;
    
    private decimal vlrRemunOEField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codCateg {
        get {
            return this.codCategField;
        }
        set {
            this.codCategField = value;
        }
    }
    
    /// <remarks/>
    public decimal vlrRemunOE {
        get {
            return this.vlrRemunOEField;
        }
        set {
            this.vlrRemunOEField = value;
        }
    }
}


public partial class eSocialEvtRemunIdeTrabalhadorInfoComplem {
    
    private string nmTrabField;
    
    private System.DateTime dtNasctoField;
    
    private eSocialEvtRemunIdeTrabalhadorInfoComplemSucessaoVinc sucessaoVincField;
    
    /// <remarks/>
    public string nmTrab {
        get {
            return this.nmTrabField;
        }
        set {
            this.nmTrabField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtNascto {
        get {
            return this.dtNasctoField;
        }
        set {
            this.dtNasctoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtRemunIdeTrabalhadorInfoComplemSucessaoVinc sucessaoVinc {
        get {
            return this.sucessaoVincField;
        }
        set {
            this.sucessaoVincField = value;
        }
    }
}


public partial class eSocialEvtRemunIdeTrabalhadorInfoComplemSucessaoVinc {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    private string matricAntField;
    
    private System.DateTime dtAdmField;
    
    private string observacaoField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
    
    /// <remarks/>
    public string matricAnt {
        get {
            return this.matricAntField;
        }
        set {
            this.matricAntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtAdm {
        get {
            return this.dtAdmField;
        }
        set {
            this.dtAdmField = value;
        }
    }
    
    /// <remarks/>
    public string observacao {
        get {
            return this.observacaoField;
        }
        set {
            this.observacaoField = value;
        }
    }
}


public partial class eSocialEvtRemunDmDev {
    
    private string ideDmDevField;
    
    private string codCategField;
    
    private eSocialEvtRemunDmDevIdeEstabLot[] infoPerApurField;
    
    private eSocialEvtRemunDmDevIdeADC[] infoPerAntField;
    
    private eSocialEvtRemunDmDevInfoComplCont infoComplContField;
    
    /// <remarks/>
    public string ideDmDev {
        get {
            return this.ideDmDevField;
        }
        set {
            this.ideDmDevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codCateg {
        get {
            return this.codCategField;
        }
        set {
            this.codCategField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ideEstabLot", IsNullable=false)]
    public eSocialEvtRemunDmDevIdeEstabLot[] infoPerApur {
        get {
            return this.infoPerApurField;
        }
        set {
            this.infoPerApurField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ideADC", IsNullable=false)]
    public eSocialEvtRemunDmDevIdeADC[] infoPerAnt {
        get {
            return this.infoPerAntField;
        }
        set {
            this.infoPerAntField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtRemunDmDevInfoComplCont infoComplCont {
        get {
            return this.infoComplContField;
        }
        set {
            this.infoComplContField = value;
        }
    }
}


public partial class eSocialEvtRemunDmDevIdeEstabLot {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    private string codLotacaoField;
    
    private sbyte qtdDiasAvField;
    
    private bool qtdDiasAvFieldSpecified;
    
    private eSocialEvtRemunDmDevIdeEstabLotRemunPerApur[] remunPerApurField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
    
    /// <remarks/>
    public string codLotacao {
        get {
            return this.codLotacaoField;
        }
        set {
            this.codLotacaoField = value;
        }
    }
    
    /// <remarks/>
    public sbyte qtdDiasAv {
        get {
            return this.qtdDiasAvField;
        }
        set {
            this.qtdDiasAvField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool qtdDiasAvSpecified {
        get {
            return this.qtdDiasAvFieldSpecified;
        }
        set {
            this.qtdDiasAvFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("remunPerApur")]
    public eSocialEvtRemunDmDevIdeEstabLotRemunPerApur[] remunPerApur {
        get {
            return this.remunPerApurField;
        }
        set {
            this.remunPerApurField = value;
        }
    }
}


public partial class eSocialEvtRemunDmDevIdeEstabLotRemunPerApur {
    
    private string matriculaField;
    
    private sbyte indSimplesField;
    
    private bool indSimplesFieldSpecified;
    
    private T_itensRemun[] itensRemunField;
    
    private T_infoAgNocivo infoAgNocivoField;
    
    /// <remarks/>
    public string matricula {
        get {
            return this.matriculaField;
        }
        set {
            this.matriculaField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indSimples {
        get {
            return this.indSimplesField;
        }
        set {
            this.indSimplesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indSimplesSpecified {
        get {
            return this.indSimplesFieldSpecified;
        }
        set {
            this.indSimplesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("itensRemun")]
    public T_itensRemun[] itensRemun {
        get {
            return this.itensRemunField;
        }
        set {
            this.itensRemunField = value;
        }
    }
    
    /// <remarks/>
    public T_infoAgNocivo infoAgNocivo {
        get {
            return this.infoAgNocivoField;
        }
        set {
            this.infoAgNocivoField = value;
        }
    }
}


public partial class eSocialEvtRemunDmDevIdeADC {
    
    private System.DateTime dtAcConvField;
    
    private bool dtAcConvFieldSpecified;
    
    private TS_tpAcConv tpAcConvField;
    
    private string dscField;
    
    private TS_sim_nao remunSucField;
    
    private eSocialEvtRemunDmDevIdeADCIdePeriodo[] idePeriodoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtAcConv {
        get {
            return this.dtAcConvField;
        }
        set {
            this.dtAcConvField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dtAcConvSpecified {
        get {
            return this.dtAcConvFieldSpecified;
        }
        set {
            this.dtAcConvFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public TS_tpAcConv tpAcConv {
        get {
            return this.tpAcConvField;
        }
        set {
            this.tpAcConvField = value;
        }
    }
    
    /// <remarks/>
    public string dsc {
        get {
            return this.dscField;
        }
        set {
            this.dscField = value;
        }
    }
    
    /// <remarks/>
    public TS_sim_nao remunSuc {
        get {
            return this.remunSucField;
        }
        set {
            this.remunSucField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("idePeriodo")]
    public eSocialEvtRemunDmDevIdeADCIdePeriodo[] idePeriodo {
        get {
            return this.idePeriodoField;
        }
        set {
            this.idePeriodoField = value;
        }
    }
}


public enum TS_tpAcConv {
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    B,
    
    /// <remarks/>
    C,
    
    /// <remarks/>
    D,
    
    /// <remarks/>
    E,
    
    /// <remarks/>
    F,
    
    /// <remarks/>
    G,
    
    /// <remarks/>
    H,
    
    /// <remarks/>
    I,
}


public enum TS_sim_nao {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    N,
}


public partial class eSocialEvtRemunDmDevIdeADCIdePeriodo {
    
    private string perRefField;
    
    private eSocialEvtRemunDmDevIdeADCIdePeriodoIdeEstabLot[] ideEstabLotField;
    
    /// <remarks/>
    public string perRef {
        get {
            return this.perRefField;
        }
        set {
            this.perRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ideEstabLot")]
    public eSocialEvtRemunDmDevIdeADCIdePeriodoIdeEstabLot[] ideEstabLot {
        get {
            return this.ideEstabLotField;
        }
        set {
            this.ideEstabLotField = value;
        }
    }
}


public partial class eSocialEvtRemunDmDevIdeADCIdePeriodoIdeEstabLot {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    private string codLotacaoField;
    
    private eSocialEvtRemunDmDevIdeADCIdePeriodoIdeEstabLotRemunPerAnt[] remunPerAntField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
    
    /// <remarks/>
    public string codLotacao {
        get {
            return this.codLotacaoField;
        }
        set {
            this.codLotacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("remunPerAnt")]
    public eSocialEvtRemunDmDevIdeADCIdePeriodoIdeEstabLotRemunPerAnt[] remunPerAnt {
        get {
            return this.remunPerAntField;
        }
        set {
            this.remunPerAntField = value;
        }
    }
}


public partial class eSocialEvtRemunDmDevIdeADCIdePeriodoIdeEstabLotRemunPerAnt {
    
    private string matriculaField;
    
    private sbyte indSimplesField;
    
    private bool indSimplesFieldSpecified;
    
    private T_itensRemun[] itensRemunField;
    
    private T_infoAgNocivo infoAgNocivoField;
    
    /// <remarks/>
    public string matricula {
        get {
            return this.matriculaField;
        }
        set {
            this.matriculaField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indSimples {
        get {
            return this.indSimplesField;
        }
        set {
            this.indSimplesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indSimplesSpecified {
        get {
            return this.indSimplesFieldSpecified;
        }
        set {
            this.indSimplesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("itensRemun")]
    public T_itensRemun[] itensRemun {
        get {
            return this.itensRemunField;
        }
        set {
            this.itensRemunField = value;
        }
    }
    
    /// <remarks/>
    public T_infoAgNocivo infoAgNocivo {
        get {
            return this.infoAgNocivoField;
        }
        set {
            this.infoAgNocivoField = value;
        }
    }
}


public partial class eSocialEvtRemunDmDevInfoComplCont {
    
    private string codCBOField;
    
    private sbyte natAtividadeField;
    
    private bool natAtividadeFieldSpecified;
    
    private sbyte qtdDiasTrabField;
    
    private bool qtdDiasTrabFieldSpecified;
    
    /// <remarks/>
    public string codCBO {
        get {
            return this.codCBOField;
        }
        set {
            this.codCBOField = value;
        }
    }
    
    /// <remarks/>
    public sbyte natAtividade {
        get {
            return this.natAtividadeField;
        }
        set {
            this.natAtividadeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool natAtividadeSpecified {
        get {
            return this.natAtividadeFieldSpecified;
        }
        set {
            this.natAtividadeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public sbyte qtdDiasTrab {
        get {
            return this.qtdDiasTrabField;
        }
        set {
            this.qtdDiasTrabField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool qtdDiasTrabSpecified {
        get {
            return this.qtdDiasTrabFieldSpecified;
        }
        set {
            this.qtdDiasTrabFieldSpecified = value;
        }
    }
}
}