//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace BibliotecaEsocial.Model.S1298
{


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtReabreEvPer/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtReabreEvPer/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtReabreEvPer evtReabreEvPerField;
    
    /// <remarks/>
    public eSocialEvtReabreEvPer evtReabreEvPer {
        get {
            return this.evtReabreEvPerField;
        }
        set {
            this.evtReabreEvPerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtReabreEvPer/v_S_01_00_00")]
public partial class eSocialEvtReabreEvPer {
    
    private T_ideEvento_folha_sem_retificacao ideEventoField;
    
    private T_ideEmpregador ideEmpregadorField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_folha_sem_retificacao ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_folha_sem_retificacao {
    
    private sbyte indApuracaoField;
    
    private string perApurField;
    
    private sbyte indGuiaField;
    
    private bool indGuiaFieldSpecified;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indApuracao {
        get {
            return this.indApuracaoField;
        }
        set {
            this.indApuracaoField = value;
        }
    }
    
    /// <remarks/>
    public string perApur {
        get {
            return this.perApurField;
        }
        set {
            this.perApurField = value;
        }
    }
    
    /// <remarks/>
    public sbyte indGuia {
        get {
            return this.indGuiaField;
        }
        set {
            this.indGuiaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indGuiaSpecified {
        get {
            return this.indGuiaFieldSpecified;
        }
        set {
            this.indGuiaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_ideEmpregador {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}
}