//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace BibliotecaEsocial.Model.S2298
{


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtReintegr/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtReintegr/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtReintegr evtReintegrField;
    
    /// <remarks/>
    public eSocialEvtReintegr evtReintegr {
        get {
            return this.evtReintegrField;
        }
        set {
            this.evtReintegrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtReintegr/v_S_01_00_00")]
public partial class eSocialEvtReintegr {
    
    private T_ideEvento_trab ideEventoField;
    
    private T_ideEmpregador ideEmpregadorField;
    
    private T_ideVinculo ideVinculoField;
    
    private eSocialEvtReintegrInfoReintegr infoReintegrField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_trab ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public T_ideVinculo ideVinculo {
        get {
            return this.ideVinculoField;
        }
        set {
            this.ideVinculoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtReintegrInfoReintegr infoReintegr {
        get {
            return this.infoReintegrField;
        }
        set {
            this.infoReintegrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_trab {
    
    private sbyte indRetifField;
    
    private string nrReciboField;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indRetif {
        get {
            return this.indRetifField;
        }
        set {
            this.indRetifField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecibo {
        get {
            return this.nrReciboField;
        }
        set {
            this.nrReciboField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_ideVinculo {
    
    private string cpfTrabField;
    
    private string matriculaField;
    
    /// <remarks/>
    public string cpfTrab {
        get {
            return this.cpfTrabField;
        }
        set {
            this.cpfTrabField = value;
        }
    }
    
    /// <remarks/>
    public string matricula {
        get {
            return this.matriculaField;
        }
        set {
            this.matriculaField = value;
        }
    }
}


public partial class T_ideEmpregador {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}

public partial class eSocialEvtReintegrInfoReintegr {
    
    private sbyte tpReintField;
    
    private string nrProcJudField;
    
    private string nrLeiAnistiaField;
    
    private System.DateTime dtEfetRetornoField;
    
    private System.DateTime dtEfeitoField;
    
    /// <remarks/>
    public sbyte tpReint {
        get {
            return this.tpReintField;
        }
        set {
            this.tpReintField = value;
        }
    }
    
    /// <remarks/>
    public string nrProcJud {
        get {
            return this.nrProcJudField;
        }
        set {
            this.nrProcJudField = value;
        }
    }
    
    /// <remarks/>
    public string nrLeiAnistia {
        get {
            return this.nrLeiAnistiaField;
        }
        set {
            this.nrLeiAnistiaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtEfetRetorno {
        get {
            return this.dtEfetRetornoField;
        }
        set {
            this.dtEfetRetornoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtEfeito {
        get {
            return this.dtEfeitoField;
        }
        set {
            this.dtEfeitoField = value;
        }
    }
}
}