//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace BibliotecaEsocial.Model.S1070
{


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabProcesso/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTabProcesso/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtTabProcesso evtTabProcessoField;
    
    /// <remarks/>
    public eSocialEvtTabProcesso evtTabProcesso {
        get {
            return this.evtTabProcessoField;
        }
        set {
            this.evtTabProcessoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabProcesso/v_S_01_00_00")]
public partial class eSocialEvtTabProcesso {
    
    private T_ideEvento_evtTab ideEventoField;
    
    private T_ideEmpregador ideEmpregadorField;
    
    private eSocialEvtTabProcessoInfoProcesso infoProcessoField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_evtTab ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtTabProcessoInfoProcesso infoProcesso {
        get {
            return this.infoProcessoField;
        }
        set {
            this.infoProcessoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_evtTab {
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_novaValidade {
    
    private string iniValidField;
    
    private string fimValidField;
    
    /// <remarks/>
    public string iniValid {
        get {
            return this.iniValidField;
        }
        set {
            this.iniValidField = value;
        }
    }
    
    /// <remarks/>
    public string fimValid {
        get {
            return this.fimValidField;
        }
        set {
            this.fimValidField = value;
        }
    }
}


public partial class T_dadosProc {
    
    private sbyte indAutoriaField;
    
    private bool indAutoriaFieldSpecified;
    
    private sbyte indMatProcField;
    
    private string observacaoField;
    
    private T_dadosProcDadosProcJud dadosProcJudField;
    
    private T_dadosProcInfoSusp[] infoSuspField;
    
    /// <remarks/>
    public sbyte indAutoria {
        get {
            return this.indAutoriaField;
        }
        set {
            this.indAutoriaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indAutoriaSpecified {
        get {
            return this.indAutoriaFieldSpecified;
        }
        set {
            this.indAutoriaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public sbyte indMatProc {
        get {
            return this.indMatProcField;
        }
        set {
            this.indMatProcField = value;
        }
    }
    
    /// <remarks/>
    public string observacao {
        get {
            return this.observacaoField;
        }
        set {
            this.observacaoField = value;
        }
    }
    
    /// <remarks/>
    public T_dadosProcDadosProcJud dadosProcJud {
        get {
            return this.dadosProcJudField;
        }
        set {
            this.dadosProcJudField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("infoSusp")]
    public T_dadosProcInfoSusp[] infoSusp {
        get {
            return this.infoSuspField;
        }
        set {
            this.infoSuspField = value;
        }
    }
}


public partial class T_dadosProcDadosProcJud {
    
    private TS_uf ufVaraField;
    
    private string codMunicField;
    
    private string idVaraField;
    
    /// <remarks/>
    public TS_uf ufVara {
        get {
            return this.ufVaraField;
        }
        set {
            this.ufVaraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codMunic {
        get {
            return this.codMunicField;
        }
        set {
            this.codMunicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string idVara {
        get {
            return this.idVaraField;
        }
        set {
            this.idVaraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTabProcesso/v_S_01_00_00")]
public enum TS_uf {
    
    /// <remarks/>
    AC,
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    AP,
    
    /// <remarks/>
    AM,
    
    /// <remarks/>
    BA,
    
    /// <remarks/>
    CE,
    
    /// <remarks/>
    DF,
    
    /// <remarks/>
    ES,
    
    /// <remarks/>
    GO,
    
    /// <remarks/>
    MA,
    
    /// <remarks/>
    MT,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MG,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    PB,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    PE,
    
    /// <remarks/>
    PI,
    
    /// <remarks/>
    RJ,
    
    /// <remarks/>
    RN,
    
    /// <remarks/>
    RS,
    
    /// <remarks/>
    RO,
    
    /// <remarks/>
    RR,
    
    /// <remarks/>
    SC,
    
    /// <remarks/>
    SP,
    
    /// <remarks/>
    SE,
    
    /// <remarks/>
    TO,
}


public partial class T_dadosProcInfoSusp {
    
    private string codSuspField;
    
    private T_dadosProcInfoSuspIndSusp indSuspField;
    
    private System.DateTime dtDecisaoField;
    
    private TS_sim_nao indDepositoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codSusp {
        get {
            return this.codSuspField;
        }
        set {
            this.codSuspField = value;
        }
    }
    
    /// <remarks/>
    public T_dadosProcInfoSuspIndSusp indSusp {
        get {
            return this.indSuspField;
        }
        set {
            this.indSuspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtDecisao {
        get {
            return this.dtDecisaoField;
        }
        set {
            this.dtDecisaoField = value;
        }
    }
    
    /// <remarks/>
    public TS_sim_nao indDeposito {
        get {
            return this.indDepositoField;
        }
        set {
            this.indDepositoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabProcesso/v_S_01_00_00")]
public enum T_dadosProcInfoSuspIndSusp {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("01")]
    Item01,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("02")]
    Item02,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("03")]
    Item03,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("04")]
    Item04,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("05")]
    Item05,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("08")]
    Item08,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("09")]
    Item09,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("90")]
    Item90,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("92")]
    Item92,
}


public enum TS_sim_nao {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    N,
}


public partial class T_ideProcesso {
    
    private sbyte tpProcField;
    
    private string nrProcField;
    
    private string iniValidField;
    
    private string fimValidField;
    
    /// <remarks/>
    public sbyte tpProc {
        get {
            return this.tpProcField;
        }
        set {
            this.tpProcField = value;
        }
    }
    
    /// <remarks/>
    public string nrProc {
        get {
            return this.nrProcField;
        }
        set {
            this.nrProcField = value;
        }
    }
    
    /// <remarks/>
    public string iniValid {
        get {
            return this.iniValidField;
        }
        set {
            this.iniValidField = value;
        }
    }
    
    /// <remarks/>
    public string fimValid {
        get {
            return this.fimValidField;
        }
        set {
            this.fimValidField = value;
        }
    }
}


public partial class T_ideEmpregador {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtTabProcessoInfoProcesso {
    
    private object itemField;
    private object Alteracao;
    private object Exclusao;
    private object Inclusao;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("myalteracao", typeof(eSocialEvtTabProcessoInfoProcessoAlteracao))]
    [System.Xml.Serialization.XmlElementAttribute("myexclusao", typeof(eSocialEvtTabProcessoInfoProcessoExclusao))]
    [System.Xml.Serialization.XmlElementAttribute("myinclusao", typeof(eSocialEvtTabProcessoInfoProcessoInclusao))]
    public object Item
    {
        get { return this.itemField; }
        set { this.itemField = value; }
    }

    public object alteracao
        {
        get
        {
            return this.Alteracao;
        }
        set
        {
            this.Alteracao = value;
        }
    }
    public object exclusao
        {
        get
        {
            return this.Exclusao;
        }
        set
        {
            this.Exclusao = value;
        }
    }
    public object inclusao
        {
        get
        {
            return this.Inclusao;
        }
        set
        {
            this.Inclusao = value;
        }
    }
    }


public partial class eSocialEvtTabProcessoInfoProcessoAlteracao {
    
    private T_ideProcesso ideProcessoField;
    
    private T_dadosProc dadosProcField;
    
    private T_novaValidade novaValidadeField;
    
    /// <remarks/>
    public T_ideProcesso ideProcesso {
        get {
            return this.ideProcessoField;
        }
        set {
            this.ideProcessoField = value;
        }
    }
    
    /// <remarks/>
    public T_dadosProc dadosProc {
        get {
            return this.dadosProcField;
        }
        set {
            this.dadosProcField = value;
        }
    }
    
    /// <remarks/>
    public T_novaValidade novaValidade {
        get {
            return this.novaValidadeField;
        }
        set {
            this.novaValidadeField = value;
        }
    }
}


public partial class eSocialEvtTabProcessoInfoProcessoExclusao {
    
    private T_ideProcesso ideProcessoField;
    
    /// <remarks/>
    public T_ideProcesso ideProcesso {
        get {
            return this.ideProcessoField;
        }
        set {
            this.ideProcessoField = value;
        }
    }
}


public partial class eSocialEvtTabProcessoInfoProcessoInclusao {
    
    private T_ideProcesso ideProcessoField;
    
    private T_dadosProc dadosProcField;
    
    /// <remarks/>
    public T_ideProcesso ideProcesso {
        get {
            return this.ideProcessoField;
        }
        set {
            this.ideProcessoField = value;
        }
    }
    
    /// <remarks/>
    public T_dadosProc dadosProc {
        get {
            return this.dadosProcField;
        }
        set {
            this.dadosProcField = value;
        }
    }
}
}