//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace BibliotecaEsocial.Model.S2306
{


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContr/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContr/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtTSVAltContr evtTSVAltContrField;
    
    /// <remarks/>
    public eSocialEvtTSVAltContr evtTSVAltContr {
        get {
            return this.evtTSVAltContrField;
        }
        set {
            this.evtTSVAltContrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContr/v_S_01_00_00")]
public partial class eSocialEvtTSVAltContr {
    
    private T_ideEvento_trab ideEventoField;
    
    private T_ideEmpregador ideEmpregadorField;
    
    private T_ideTrabSemVinculo ideTrabSemVinculoField;
    
    private eSocialEvtTSVAltContrInfoTSVAlteracao infoTSVAlteracaoField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_trab ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public T_ideTrabSemVinculo ideTrabSemVinculo {
        get {
            return this.ideTrabSemVinculoField;
        }
        set {
            this.ideTrabSemVinculoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtTSVAltContrInfoTSVAlteracao infoTSVAlteracao {
        get {
            return this.infoTSVAlteracaoField;
        }
        set {
            this.infoTSVAlteracaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_trab {
    
    private sbyte indRetifField;
    
    private string nrReciboField;
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte indRetif {
        get {
            return this.indRetifField;
        }
        set {
            this.indRetifField = value;
        }
    }
    
    /// <remarks/>
    public string nrRecibo {
        get {
            return this.nrReciboField;
        }
        set {
            this.nrReciboField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_infoEstagiario {
    
    private T_infoEstagiarioNatEstagio natEstagioField;
    
    private sbyte nivEstagioField;
    
    private bool nivEstagioFieldSpecified;
    
    private string areaAtuacaoField;
    
    private string nrApolField;
    
    private System.DateTime dtPrevTermField;
    
    private T_infoEstagiarioInstEnsino instEnsinoField;
    
    private T_infoEstagiarioAgeIntegracao ageIntegracaoField;
    
    private T_infoEstagiarioSupervisorEstagio supervisorEstagioField;
    
    /// <remarks/>
    public T_infoEstagiarioNatEstagio natEstagio {
        get {
            return this.natEstagioField;
        }
        set {
            this.natEstagioField = value;
        }
    }
    
    /// <remarks/>
    public sbyte nivEstagio {
        get {
            return this.nivEstagioField;
        }
        set {
            this.nivEstagioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nivEstagioSpecified {
        get {
            return this.nivEstagioFieldSpecified;
        }
        set {
            this.nivEstagioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string areaAtuacao {
        get {
            return this.areaAtuacaoField;
        }
        set {
            this.areaAtuacaoField = value;
        }
    }
    
    /// <remarks/>
    public string nrApol {
        get {
            return this.nrApolField;
        }
        set {
            this.nrApolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtPrevTerm {
        get {
            return this.dtPrevTermField;
        }
        set {
            this.dtPrevTermField = value;
        }
    }
    
    /// <remarks/>
    public T_infoEstagiarioInstEnsino instEnsino {
        get {
            return this.instEnsinoField;
        }
        set {
            this.instEnsinoField = value;
        }
    }
    
    /// <remarks/>
    public T_infoEstagiarioAgeIntegracao ageIntegracao {
        get {
            return this.ageIntegracaoField;
        }
        set {
            this.ageIntegracaoField = value;
        }
    }
    
    /// <remarks/>
    public T_infoEstagiarioSupervisorEstagio supervisorEstagio {
        get {
            return this.supervisorEstagioField;
        }
        set {
            this.supervisorEstagioField = value;
        }
    }
}


public enum T_infoEstagiarioNatEstagio {
    
    /// <remarks/>
    O,
    
    /// <remarks/>
    N,
}


public partial class T_infoEstagiarioInstEnsino {
    
    private string cnpjInstEnsinoField;
    
    private string nmRazaoField;
    
    private string dscLogradField;
    
    private string nrLogradField;
    
    private string bairroField;
    
    private string cepField;
    
    private string codMunicField;
    
    private TS_uf ufField;
    
    private bool ufFieldSpecified;
    
    /// <remarks/>
    public string cnpjInstEnsino {
        get {
            return this.cnpjInstEnsinoField;
        }
        set {
            this.cnpjInstEnsinoField = value;
        }
    }
    
    /// <remarks/>
    public string nmRazao {
        get {
            return this.nmRazaoField;
        }
        set {
            this.nmRazaoField = value;
        }
    }
    
    /// <remarks/>
    public string dscLograd {
        get {
            return this.dscLogradField;
        }
        set {
            this.dscLogradField = value;
        }
    }
    
    /// <remarks/>
    public string nrLograd {
        get {
            return this.nrLogradField;
        }
        set {
            this.nrLogradField = value;
        }
    }
    
    /// <remarks/>
    public string bairro {
        get {
            return this.bairroField;
        }
        set {
            this.bairroField = value;
        }
    }
    
    /// <remarks/>
    public string cep {
        get {
            return this.cepField;
        }
        set {
            this.cepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codMunic {
        get {
            return this.codMunicField;
        }
        set {
            this.codMunicField = value;
        }
    }
    
    /// <remarks/>
    public TS_uf uf {
        get {
            return this.ufField;
        }
        set {
            this.ufField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ufSpecified {
        get {
            return this.ufFieldSpecified;
        }
        set {
            this.ufFieldSpecified = value;
        }
    }
}


public enum TS_uf {
    
    /// <remarks/>
    AC,
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    AP,
    
    /// <remarks/>
    AM,
    
    /// <remarks/>
    BA,
    
    /// <remarks/>
    CE,
    
    /// <remarks/>
    DF,
    
    /// <remarks/>
    ES,
    
    /// <remarks/>
    GO,
    
    /// <remarks/>
    MA,
    
    /// <remarks/>
    MT,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MG,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    PB,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    PE,
    
    /// <remarks/>
    PI,
    
    /// <remarks/>
    RJ,
    
    /// <remarks/>
    RN,
    
    /// <remarks/>
    RS,
    
    /// <remarks/>
    RO,
    
    /// <remarks/>
    RR,
    
    /// <remarks/>
    SC,
    
    /// <remarks/>
    SP,
    
    /// <remarks/>
    SE,
    
    /// <remarks/>
    TO,
}


public partial class T_infoEstagiarioAgeIntegracao {
    
    private string cnpjAgntIntegField;
    
    /// <remarks/>
    public string cnpjAgntInteg {
        get {
            return this.cnpjAgntIntegField;
        }
        set {
            this.cnpjAgntIntegField = value;
        }
    }
}


public partial class T_infoEstagiarioSupervisorEstagio {
    
    private string cpfSupervisorField;
    
    /// <remarks/>
    public string cpfSupervisor {
        get {
            return this.cpfSupervisorField;
        }
        set {
            this.cpfSupervisorField = value;
        }
    }
}


public partial class T_remuneracao {
    
    private decimal vrSalFxField;
    
    private sbyte undSalFixoField;
    
    private string dscSalVarField;
    
    /// <remarks/>
    public decimal vrSalFx {
        get {
            return this.vrSalFxField;
        }
        set {
            this.vrSalFxField = value;
        }
    }
    
    /// <remarks/>
    public sbyte undSalFixo {
        get {
            return this.undSalFixoField;
        }
        set {
            this.undSalFixoField = value;
        }
    }
    
    /// <remarks/>
    public string dscSalVar {
        get {
            return this.dscSalVarField;
        }
        set {
            this.dscSalVarField = value;
        }
    }
}


public partial class T_ideTrabSemVinculo {
    
    private string cpfTrabField;
    
    private string matriculaField;
    
    private string codCategField;
    
    /// <remarks/>
    public string cpfTrab {
        get {
            return this.cpfTrabField;
        }
        set {
            this.cpfTrabField = value;
        }
    }
    
    /// <remarks/>
    public string matricula {
        get {
            return this.matriculaField;
        }
        set {
            this.matriculaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codCateg {
        get {
            return this.codCategField;
        }
        set {
            this.codCategField = value;
        }
    }
}


public partial class T_ideEmpregador {
    
    private sbyte tpInscField;
    
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}


public partial class eSocialEvtTSVAltContrInfoTSVAlteracao {
    
    private System.DateTime dtAlteracaoField;
    
    private sbyte natAtividadeField;
    
    private bool natAtividadeFieldSpecified;
    
    private eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementares infoComplementaresField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dtAlteracao {
        get {
            return this.dtAlteracaoField;
        }
        set {
            this.dtAlteracaoField = value;
        }
    }
    
    /// <remarks/>
    public sbyte natAtividade {
        get {
            return this.natAtividadeField;
        }
        set {
            this.natAtividadeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool natAtividadeSpecified {
        get {
            return this.natAtividadeFieldSpecified;
        }
        set {
            this.natAtividadeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementares infoComplementares {
        get {
            return this.infoComplementaresField;
        }
        set {
            this.infoComplementaresField = value;
        }
    }
}


public partial class eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementares {
    
    private eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresCargoFuncao cargoFuncaoField;
    
    private T_remuneracao remuneracaoField;
    
    private eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoDirigenteSindical infoDirigenteSindicalField;
    
    private eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoTrabCedido infoTrabCedidoField;
    
    private eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoMandElet infoMandEletField;
    
    private T_infoEstagiario infoEstagiarioField;
    
    /// <remarks/>
    public eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresCargoFuncao cargoFuncao {
        get {
            return this.cargoFuncaoField;
        }
        set {
            this.cargoFuncaoField = value;
        }
    }
    
    /// <remarks/>
    public T_remuneracao remuneracao {
        get {
            return this.remuneracaoField;
        }
        set {
            this.remuneracaoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoDirigenteSindical infoDirigenteSindical {
        get {
            return this.infoDirigenteSindicalField;
        }
        set {
            this.infoDirigenteSindicalField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoTrabCedido infoTrabCedido {
        get {
            return this.infoTrabCedidoField;
        }
        set {
            this.infoTrabCedidoField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoMandElet infoMandElet {
        get {
            return this.infoMandEletField;
        }
        set {
            this.infoMandEletField = value;
        }
    }
    
    /// <remarks/>
    public T_infoEstagiario infoEstagiario {
        get {
            return this.infoEstagiarioField;
        }
        set {
            this.infoEstagiarioField = value;
        }
    }
}


public partial class eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresCargoFuncao {
    
    private string nmCargoField;
    
    private string cBOCargoField;
    
    private string nmFuncaoField;
    
    private string cBOFuncaoField;
    
    /// <remarks/>
    public string nmCargo {
        get {
            return this.nmCargoField;
        }
        set {
            this.nmCargoField = value;
        }
    }
    
    /// <remarks/>
    public string CBOCargo {
        get {
            return this.cBOCargoField;
        }
        set {
            this.cBOCargoField = value;
        }
    }
    
    /// <remarks/>
    public string nmFuncao {
        get {
            return this.nmFuncaoField;
        }
        set {
            this.nmFuncaoField = value;
        }
    }
    
    /// <remarks/>
    public string CBOFuncao {
        get {
            return this.cBOFuncaoField;
        }
        set {
            this.cBOFuncaoField = value;
        }
    }
}


public partial class eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoDirigenteSindical {
    
    private sbyte tpRegPrevField;
    
    /// <remarks/>
    public sbyte tpRegPrev {
        get {
            return this.tpRegPrevField;
        }
        set {
            this.tpRegPrevField = value;
        }
    }
}


public partial class eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoTrabCedido {
    
    private sbyte tpRegPrevField;
    
    /// <remarks/>
    public sbyte tpRegPrev {
        get {
            return this.tpRegPrevField;
        }
        set {
            this.tpRegPrevField = value;
        }
    }
}


public partial class eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoMandElet {
    
    private TS_indRemunCargo indRemunCargoField;
    
    private bool indRemunCargoFieldSpecified;
    
    private sbyte tpRegPrevField;
    
    /// <remarks/>
    public TS_indRemunCargo indRemunCargo {
        get {
            return this.indRemunCargoField;
        }
        set {
            this.indRemunCargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indRemunCargoSpecified {
        get {
            return this.indRemunCargoFieldSpecified;
        }
        set {
            this.indRemunCargoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpRegPrev {
        get {
            return this.tpRegPrevField;
        }
        set {
            this.tpRegPrevField = value;
        }
    }
}


public enum TS_indRemunCargo {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    N,
}
}