//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace BibliotecaEsocial.Model.S1020
{


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabLotacao/v_S_01_00_00")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTabLotacao/v_S_01_00_00", IsNullable=false)]
public partial class eSocial {
    
    private eSocialEvtTabLotacao evtTabLotacaoField;
    
    /// <remarks/>
    public eSocialEvtTabLotacao evtTabLotacao {
        get {
            return this.evtTabLotacaoField;
        }
        set {
            this.evtTabLotacaoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabLotacao/v_S_01_00_00")]
public partial class eSocialEvtTabLotacao {
    
    private T_ideEvento_evtTab ideEventoField;
    
    private T_ideEmpregador ideEmpregadorField;
    
    private eSocialEvtTabLotacaoInfoLotacao infoLotacaoField;
    
    private string idField;
    
    /// <remarks/>
    public T_ideEvento_evtTab ideEvento {
        get {
            return this.ideEventoField;
        }
        set {
            this.ideEventoField = value;
        }
    }
    
    /// <remarks/>
    public T_ideEmpregador ideEmpregador {
        get {
            return this.ideEmpregadorField;
        }
        set {
            this.ideEmpregadorField = value;
        }
    }
    
    /// <remarks/>
    public eSocialEvtTabLotacaoInfoLotacao infoLotacao {
        get {
            return this.infoLotacaoField;
        }
        set {
            this.infoLotacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


public partial class T_ideEvento_evtTab {
    
    private sbyte tpAmbField;
    
    private sbyte procEmiField;
    
    private string verProcField;
    
    /// <remarks/>
    public sbyte tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public sbyte procEmi {
        get {
            return this.procEmiField;
        }
        set {
            this.procEmiField = value;
        }
    }
    
    /// <remarks/>
    public string verProc {
        get {
            return this.verProcField;
        }
        set {
            this.verProcField = value;
        }
    }
}


public partial class T_novaValidade {
    
    private string iniValidField;
    
    private string fimValidField;
    
    /// <remarks/>
    public string iniValid {
        get {
            return this.iniValidField;
        }
        set {
            this.iniValidField = value;
        }
    }
    
    /// <remarks/>
    public string fimValid {
        get {
            return this.fimValidField;
        }
        set {
            this.fimValidField = value;
        }
    }
}


public partial class T_dadosLotacao {
    
    private string tpLotacaoField;
    
    private sbyte tpInscField;
    
    private bool tpInscFieldSpecified;
    
    private string nrInscField;
    
    private T_dadosLotacaoFpasLotacao fpasLotacaoField;
    
    private T_dadosLotacaoInfoEmprParcial infoEmprParcialField;
    
    private T_dadosLotacaoDadosOpPort dadosOpPortField;
    
    /// <remarks/>
    public string tpLotacao {
        get {
            return this.tpLotacaoField;
        }
        set {
            this.tpLotacaoField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tpInscSpecified {
        get {
            return this.tpInscFieldSpecified;
        }
        set {
            this.tpInscFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
    
    /// <remarks/>
    public T_dadosLotacaoFpasLotacao fpasLotacao {
        get {
            return this.fpasLotacaoField;
        }
        set {
            this.fpasLotacaoField = value;
        }
    }
    
    /// <remarks/>
    public T_dadosLotacaoInfoEmprParcial infoEmprParcial {
        get {
            return this.infoEmprParcialField;
        }
        set {
            this.infoEmprParcialField = value;
        }
    }
    
    /// <remarks/>
    public T_dadosLotacaoDadosOpPort dadosOpPort {
        get {
            return this.dadosOpPortField;
        }
        set {
            this.dadosOpPortField = value;
        }
    }
}


public partial class T_dadosLotacaoFpasLotacao {
    
    private string fpasField;
    
    private string codTercsField;
    
    private string codTercsSuspField;
    
    private T_dadosLotacaoFpasLotacaoProcJudTerceiro[] infoProcJudTerceirosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string fpas {
        get {
            return this.fpasField;
        }
        set {
            this.fpasField = value;
        }
    }
    
    /// <remarks/>
    public string codTercs {
        get {
            return this.codTercsField;
        }
        set {
            this.codTercsField = value;
        }
    }
    
    /// <remarks/>
    public string codTercsSusp {
        get {
            return this.codTercsSuspField;
        }
        set {
            this.codTercsSuspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("procJudTerceiro", IsNullable=false)]
    public T_dadosLotacaoFpasLotacaoProcJudTerceiro[] infoProcJudTerceiros {
        get {
            return this.infoProcJudTerceirosField;
        }
        set {
            this.infoProcJudTerceirosField = value;
        }
    }
}


public partial class T_dadosLotacaoFpasLotacaoProcJudTerceiro {
    
    private string codTercField;
    
    private string nrProcJudField;
    
    private string codSuspField;
    
    /// <remarks/>
    public string codTerc {
        get {
            return this.codTercField;
        }
        set {
            this.codTercField = value;
        }
    }
    
    /// <remarks/>
    public string nrProcJud {
        get {
            return this.nrProcJudField;
        }
        set {
            this.nrProcJudField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codSusp {
        get {
            return this.codSuspField;
        }
        set {
            this.codSuspField = value;
        }
    }
}


public partial class T_dadosLotacaoInfoEmprParcial {
    
    private sbyte tpInscContratField;
    
    private string nrInscContratField;
    
    private sbyte tpInscPropField;
    
    private bool tpInscPropFieldSpecified;
    
    private string nrInscPropField;
    
    /// <remarks/>
    public sbyte tpInscContrat {
        get {
            return this.tpInscContratField;
        }
        set {
            this.tpInscContratField = value;
        }
    }
    
    /// <remarks/>
    public string nrInscContrat {
        get {
            return this.nrInscContratField;
        }
        set {
            this.nrInscContratField = value;
        }
    }
    
    /// <remarks/>
    public sbyte tpInscProp {
        get {
            return this.tpInscPropField;
        }
        set {
            this.tpInscPropField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tpInscPropSpecified {
        get {
            return this.tpInscPropFieldSpecified;
        }
        set {
            this.tpInscPropFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string nrInscProp {
        get {
            return this.nrInscPropField;
        }
        set {
            this.nrInscPropField = value;
        }
    }
}


public partial class T_dadosLotacaoDadosOpPort {
    
    private sbyte aliqRatField;
    
    private decimal fapField;
    
    /// <remarks/>
    public sbyte aliqRat {
        get {
            return this.aliqRatField;
        }
        set {
            this.aliqRatField = value;
        }
    }
    
    /// <remarks/>
    public decimal fap {
        get {
            return this.fapField;
        }
        set {
            this.fapField = value;
        }
    }
}


public partial class T_ideLotacao {
    
    private string codLotacaoField;
    
    private string iniValidField;
    
    private string fimValidField;
    
    /// <remarks/>
    public string codLotacao {
        get {
            return this.codLotacaoField;
        }
        set {
            this.codLotacaoField = value;
        }
    }
    
    /// <remarks/>
    public string iniValid {
        get {
            return this.iniValidField;
        }
        set {
            this.iniValidField = value;
        }
    }
    
    /// <remarks/>
    public string fimValid {
        get {
            return this.fimValidField;
        }
        set {
            this.fimValidField = value;
        }
    }
}


public partial class T_ideEmpregador {
    
    private sbyte tpInscField;
    private string nrInscField;
    
    /// <remarks/>
    public sbyte tpInsc {
        get {
            return this.tpInscField;
        }
        set {
            this.tpInscField = value;
        }
    }
    
    /// <remarks/>
    public string nrInsc {
        get {
            return this.nrInscField;
        }
        set {
            this.nrInscField = value;
        }
    }
}

/// <remarks/>

public partial class eSocialEvtTabLotacaoInfoLotacao {
    
    private object itemField;
    private object Alteracao;
    private object Exclusao;
    private object Inclusao;

    /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("myAlteracao", typeof(eSocialEvtTabLotacaoInfoLotacaoAlteracao))]
    [System.Xml.Serialization.XmlElementAttribute("myExclusao", typeof(eSocialEvtTabLotacaoInfoLotacaoExclusao))]
    [System.Xml.Serialization.XmlElementAttribute("myInclusao", typeof(eSocialEvtTabLotacaoInfoLotacaoInclusao))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    public object alteracao
        {
        get
        {
            return this.Alteracao;
        }
        set
        {
            this.Alteracao = value;
        }
    }
    public object exclusao
        {
        get
        {
            return this.Exclusao;
        }
        set
        {
            this.Exclusao = value;
        }
    }
    public object inclusao
        {
        get
        {
            return this.Inclusao;
        }
        set
        {
            this.Inclusao = value;
        }
    }
    }

/// <remarks/>
public partial class eSocialEvtTabLotacaoInfoLotacaoAlteracao {
    
    private T_ideLotacao ideLotacaoField;
    
    private T_dadosLotacao dadosLotacaoField;
    
    private T_novaValidade novaValidadeField;
    
    /// <remarks/>
    public T_ideLotacao ideLotacao {
        get {
            return this.ideLotacaoField;
        }
        set {
            this.ideLotacaoField = value;
        }
    }
    
    /// <remarks/>
    public T_dadosLotacao dadosLotacao {
        get {
            return this.dadosLotacaoField;
        }
        set {
            this.dadosLotacaoField = value;
        }
    }
    
    /// <remarks/>
    public T_novaValidade novaValidade {
        get {
            return this.novaValidadeField;
        }
        set {
            this.novaValidadeField = value;
        }
    }
}

/// <remarks/>
public partial class eSocialEvtTabLotacaoInfoLotacaoExclusao {
    
    private T_ideLotacao ideLotacaoField;
    
    /// <remarks/>
    public T_ideLotacao ideLotacao {
        get {
            return this.ideLotacaoField;
        }
        set {
            this.ideLotacaoField = value;
        }
    }
}

/// <remarks/>

public partial class eSocialEvtTabLotacaoInfoLotacaoInclusao {
    
    private T_ideLotacao ideLotacaoField;
    
    private T_dadosLotacao dadosLotacaoField;
    
    /// <remarks/>
    public T_ideLotacao ideLotacao {
        get {
            return this.ideLotacaoField;
        }
        set {
            this.ideLotacaoField = value;
        }
    }
    
    /// <remarks/>
    public T_dadosLotacao dadosLotacao {
        get {
            return this.dadosLotacaoField;
        }
        set {
            this.dadosLotacaoField = value;
        }
    }
}
}
